# Generated by Django 3.1.2 on 2020-11-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201112_1807'),
        ('WSS', '0004_auto_20201112_1807'),
        ('events', '0002_auto_20201022_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='postermaterial',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='postersession',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='seminarmaterial',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='workshopmaterial',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AlterField(
            model_name='postersession',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.postermaterial'),
        ),
        migrations.AlterField(
            model_name='postersession',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='postersessions', to='people.speaker'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.seminarmaterial'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seminars', to='people.speaker'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.workshopmaterial'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='workshops', to='people.speaker'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='WSS.sponsor'),
        ),
    ]
