# Generated by Django 3.1.3 on 2020-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201112_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='link',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
