# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations

def forwards(apps, schema_editor):
    apps.get_model('events', 'Workshop').objects.create(
        title='test workshop',
        speaker=apps.get_model('people', 'Speaker').objects.get(name='Shahram Ghandeharizadeh')
    )
    apps.get_model('events', 'Seminar').objects.create(
        title='test seminar',
        speaker=apps.get_model('people', 'Speaker').objects.get(name='Shahram Ghandeharizadeh')
    )
    apps.get_model('events', 'PosterSession').objects.create(
        title='test poster session',
        speaker=apps.get_model('people', 'Speaker').objects.get(name='Shahram Ghandeharizadeh')
    )

def rollback(apps, schema_editor):
    apps.get_model('events', 'Workshop').objects.get(
        title='test workshop'
    ).delete()
    apps.get_model('events', 'Seminar').objects.get(
        title='test seminar'
    ).delete()
    apps.get_model('events', 'PosterSession').objects.get(
        title='test poster session'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_tag'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
