# Generated by Django 3.1.3 on 2020-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='is_keynote',
            field=models.BooleanField(default=False),
        ),
    ]
