# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Workshop = apps.get_model('events', 'Workshop')
    WSS = apps.get_model('WSS', 'WSS')
    Speaker = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    wss = WSS.objects.get(year=2020)
    ctype = ContentType.objects.get_for_model(Workshop)

    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='Conceptual Blending in Computational Creativity',
        syllabus='Modeling humans\' cognitive processes in a computable way is our goal. While machines communicate with humans, they need to understand complicated products produced by human’s creativity. Human creativity appears in music, art, jokes, novel stories, movies, and every other area. My current focus is on conceptual blending. Conceptual blending (CB) is a vital cognitive mechanism by which two or more mental spaces are integrated to produce new concepts (Fauconnier and Turner 2002), e.g., when a house and boat blend and a house-bout is created. Visual Metaphor is a similar area. Despite not all visual blends being visual metaphors, most research is conducted about advertisements and focuses on them. Creative systems can understand human creativity, produce innovative products, and enhance human creativity (The International Association for Computational Creativity (ACC)). I wish to explain this fantastic area in detail.',
        speaker=Speaker.objects.filter(name='Maryam Sadat Eslami').last()
    )
    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='بررسی تاریخچه word embeddingها و پیاده سازی پروژه تحلیل احساسات با bert',
        syllabus='We have a history of word embedding and then we go to the revolutionary technology, Bert. First we examine the structure of Bert and finally we will implement a practical and real project on Persian data.',
        speaker=Speaker.objects.filter(name='Mohammad Dehghani').last()
    )
    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='Machine Learning on Persian Text: Using Transfer Learning Word and Document Vectors(word2vec and doc2vec)',
        syllabus='Using Machine Learning in recent years has enabled computers to understand, analyze and decide better using all sorts of data, one of which is plain text data. \nIn this Workshop we will present theory and practice of using self-supervised(a form of unsupervised learning) training on massive amounts of text and use the learned material to classify news article\'s genre based only on their content. \nThe algorithms presented here are TF-IDF, word2vec and doc2vec. These are essential for understanding algorithms like BERT and GPT3. \nKnowledge of rudimentary machine learning and programming with Python is required(If you know what is classification and what Python code looks like it is enough).',
        speaker=Speaker.objects.filter(name='Mohammad Fazeli').last()
    )
    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='Towards Big Data Processing by Spark Unified Analytics Engine',
        syllabus='The world of Big Data has a new legend – Apache Spark. Apache Spark will be introduced for data exploration, analysis, and Big Data applications development. A little bit of history behind, it’s a unified analytics engine for big data processing with built-in modules for Natural Language Processing, Machine Learning, SQL Streaming and Graph Processing. It was created in over a decade at UC Berkeley by a group of talented PhD students. The main goal of the Towards Big Data Processing by Spark Unified Analytics Engine Workshop is to make the deeper understanding of the Apache Spark ecosystem and the related modules in Apache Spark among them Spark MLlib, Spark Structured Streaming and Spark SQL. The workshop will teach how to do performance tuning of Apache Spark applications and the advanced features of Apache Spark 3.',
        speaker=Speaker.objects.filter(name='Mohammad Heydari').last()
    )
    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='Transfer Learning in NLP with Huggingface',
        syllabus='Natural language processing is probably one of the main and final gateways to general intelligence and for many years, many researchers have tried to solve various puzzles in this field. In the last decade and after the dramatic growth of neural networks, natural language processing, like image processing, has benefited from the magic power of deep learning and has experienced a great leap. But the biggest revolution for the field has come in the last few years, following the rise of Transformers and the opening of the way for the use of transfer learning. So that in many language understanding tasks today, the score of fine-tuned models has exceeded the human performance, and in the text generation, models such as GPT3 compose texts that can not be distinguished from man-made texts. \nIn this workshop, we first try to take an overview of the theoretical prerequisites for transfer learning in natural language processing and the architecture of pre-trained networks, and then, using one of the hottest NLP libraries, Transformers developed by Huggingface, we can experience and touch how to use pre-trained networks (such as Bert and GPT) and fine-tune them on different NLP tasks. This workshop also addresses the challenges of using pre-trained networks and possible solutions for them, various Hugging Face capabilities, and future transfer learning trends in NLP.',
        speaker=Speaker.objects.filter(name='Mohammad Mahdi Samiei').last()
    )
    Workshop.objects.create(
        wss=wss,
        polymorphic_ctype=ctype,
        title='Vehicle Behavior Prediction in Self-driving Cars, from an Industrial Perspective',
        syllabus='Self-driving industry is approaching to the real application and will be a revolution in the transportation systems. Artificial intelligence is a core tool for building those systems which helps mitigating many difficult computer vision problems. While the advances in academia is transparent, the competition in the industry prevents revealing their recent solutions in details. In this presentation we will talk about different challenges in "vehicle trajectory prediction" task, as a building block of a self-driving vehicle. We try to present pioneering companies\' solutions to each of the mentioned challenges, based on their published papers or public presentations. This can shed light on the best practices for the prediction task.',
        speaker=Speaker.objects.filter(name='Mohammadhossein Bahari').last()
    )


def rollback(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    Workshop = apps.get_model('events', 'Workshop')
    wss = WSS.objects.get(year=2020)

    titles = [
        'Conceptual Blending in Computational Creativity',
        'بررسی تاریخچه word embeddingها و پیاده سازی پروژه تحلیل احساسات با bert',
        'Machine Learning on Persian Text: Using Transfer Learning Word and Document Vectors(word2vec and doc2vec)',
        'Towards Big Data Processing by Spark Unified Analytics Engine',
        'Transfer Learning in NLP with Huggingface',
        'Vehicle Behavior Prediction in Self-driving Cars, from an Industrial Perspective',
    ]

    Workshop.objects.filter(wss=wss, title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_fill_more_seminars'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
