# Generated by Django 3.1.3 on 2020-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_fill_workshops_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='link',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
