# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Seminar = apps.get_model('events', 'Seminar')
    WSS = apps.get_model('WSS', 'WSS')

    wss = WSS.objects.get(year=2020)

    Seminar.objects.filter(wss=wss, title='Understanding the role of training regimes continual training of neural networks').update(title='Understanding the role of training regimes in continual training of neural networks')
    Seminar.objects.filter(wss=wss, title='Algorithms vs. Mechanisms: Bayesian Blackbox Reductions in Mechanism Design').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_fill_more_seminars_2020'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
