# Generated by Django 3.1.3 on 2021-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_update_some_seminars'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='calender_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
