# Generated by Django 3.1.3 on 2022-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_fill_seminars_7th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseevent',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.WssTag'),
        ),
    ]
