# Generated by Django 3.1.3 on 2022-02-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_add_newer_7th_speaker_data'),
        ('events', '0028_add_newer_seminar_7th'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='poster_picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LabTalk',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
                ('field', models.CharField(blank=True, max_length=256)),
                ('website_link', models.URLField(blank=True, max_length=256, null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='labtalks', to='people.speaker')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.baseevent',),
        ),
    ]
