# Generated by Django 3.1.3 on 2022-02-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_add_labtalk_7th_speaker_data'),
        ('events', '0031_update_mohajerin_seminar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTable',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.baseevent')),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('speakers', models.ManyToManyField(to='people.Speaker')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events.baseevent',),
        ),
    ]
