# Generated by Django 3.1.3 on 2022-02-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_add_wss_7th_roundtable_speakers'),
        ('events', '0033_add_roundtables_7th'),
    ]

    operations = [
        migrations.AddField(
            model_name='Seminar',
            name='room',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
