# Generated by Django 3.1.3 on 2023-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_baseevent_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='feedback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='qa_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
