# Generated by Django 3.1.3 on 2023-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20230406_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='streamed_by_aparat',
            field=models.BooleanField(default=True),
        ),
    ]
