version: '3'

networks:
  app-network:
    driver: bridge

services:
  frontend:
    image: wss:frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    env_file:
      - .env
