version: '3'
networks:
  app-net:
    external: true
    name: app

services:
  frontend:
    image: wss:frontend
    container_name: frontend
    ports:
      - 3020:3000
    networks:
      - app-net
    env_file:
      - .env.frontend

  #networks:
  #  app-network:
  #    driver: bridge
