version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "5000:5000"
    networks:
      - app-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/www/static

volumes:
  staticfiles:
    external: true

networks:
  app-net:
     external: true
     name: app
