version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - /root/WSS-site/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/root/WSS-site/backend/staticfiles

volume:
  staticfiles:
    external: true