version: "3.3"

services:
  wss_backend:
    build: .
    container_name: wws_backend
    restart: always
    depends_on:
      database:
        condition: "service_healthy"
    command: >
      sh -c "
        ./manage.py migrate;
        ./manage.py compilemessages;
        ./manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8000 --timeout=90 --workers=6 --preload WSS_Site.wsgi:application;
      "
    volumes:
      - .:/app/wss/
      - ./static/:/static
      - ./media/:/media
      - /var/log/wss-back:/var/log/wss-back
      - cachedata:/cachec
    ports:
      - 8002:8000
    env_file:
      - .env

  database:
    container_name: wss_postgres
    restart: always
    image: dockerhub.ir/postgres
    volumes:
      - ./media/:/media/
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${WSS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  cachedata:

