# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations

def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    Staff.objects.create(
        name='Alireza Ilami'
    )
    Staff.objects.create(
        name='Mehdi Farvardin'
    )
    Staff.objects.create(
        name='Hossein Firooz'
    )
    Staff.objects.create(
        name='Sepehr Amini Afshar'
    )
    Staff.objects.create(
        name='Farzam Zohdinasab'
    )
    Staff.objects.create(
        name='Pooya Moeini'
    )
    Staff.objects.create(
        name='Seyed Mohammad mehdi Hatami'
    )
    Staff.objects.create(
        name='Emran Batman ghelich'
    )
    Staff.objects.create(
        name='Ahmad Salimi'
    )
    Staff.objects.create(
        name='Ali asghar Ghanati'
    )
    Staff.objects.create(
        name='Fatemeh Khashei'
    )
    Staff.objects.create(
        name='Alireza Tajmir riahi'
    )
    Staff.objects.create(
        name='Mohammad mehdi Barghi'
    )
    Staff.objects.create(
        name='Seyed Alireza Hashemi'
    )
    Staff.objects.create(
        name='Amirhossein Hadian'
    )
    Staff.objects.create(
        name='Amirmohammad Imani'
    )
    Staff.objects.create(
        name='Sajjad Rezvani'
    )
    Staff.objects.create(
        name='Shima Ramadani'
    )
    Staff.objects.create(
        name='Mehdi Jalali'
    )
    Staff.objects.create(
        name='Seyed Alireza Hosseini'
    )
    Staff.objects.create(
        name='Sara Azarnoosh'
    )
    Staff.objects.create(
        name='Dorna Dehghani'
    )
    Staff.objects.create(
        name='Ghazal Shenavar'
    )
    Staff.objects.create(
        name='Helia Akhtarkavian'
    )
    Staff.objects.create(
        name='Sabiheh Tajdari'
    )
    Staff.objects.create(
        name='Sahel Messforoosh'
    )
    Staff.objects.create(
        name='Esmaeil Pahang'
    )
    Staff.objects.create(
        name='Hamila Meili'
    )
    Staff.objects.create(
        name='Mahdieh Ebrahimpoor'
    )
    Staff.objects.create(
        name='Roya Aghvami'
    )
    Staff.objects.create(
        name='Sara Zahedi'
    )
    Staff.objects.create(
        name='Hossein Aghamohammadi'
    )
    Staff.objects.create(
        name='Vahid Zehtab'
    )
    Staff.objects.create(
        name='Amirhossein Asem Yousefi'
    )
    Staff.objects.create(
        name='Alireza Ziaei'
    )
    Staff.objects.create(
        name='Ehsan Movafagh'
    )
    Staff.objects.create(
        name='ArhsiA Akhavan'
    )

def rollback(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    Staff.objects.get(
        name='Alireza Ilami'
    ).delete()
    Staff.objects.get(
        name='Mehdi Farvardin'
    ).delete()
    Staff.objects.get(
        name='Hossein Firooz'
    ).delete()
    Staff.objects.get(
        name='Sepehr Amini Afshar'
    ).delete()
    Staff.objects.get(
        name='Farzam Zohdinasab'
    ).delete()
    Staff.objects.get(
        name='Pooya Moeini'
    ).delete()
    Staff.objects.get(
        name='Seyed Mohammad mehdi Hatami'
    ).delete()
    Staff.objects.get(
        name='Emran Batman ghelich'
    ).delete()
    Staff.objects.get(
        name='Ahmad Salimi'
    ).delete()
    Staff.objects.get(
        name='Ali asghar Ghanati'
    ).delete()
    Staff.objects.get(
        name='Fatemeh Khashei'
    ).delete()
    Staff.objects.get(
        name='Alireza Tajmir riahi'
    ).delete()
    Staff.objects.get(
        name='Mohammad mehdi Barghi'
    ).delete()
    Staff.objects.get(
        name='Seyed Alireza Hashemi'
    ).delete()
    Staff.objects.get(
        name='Amirhossein Hadian'
    ).delete()
    Staff.objects.get(
        name='Amirmohammad Imani'
    ).delete()
    Staff.objects.get(
        name='Sajjad Rezvani'
    ).delete()
    Staff.objects.get(
        name='Shima Ramadani'
    ).delete()
    Staff.objects.get(
        name='Mehdi Jalali'
    ).delete()
    Staff.objects.get(
        name='Seyed Alireza Hosseini'
    ).delete()
    Staff.objects.get(
        name='Sara Azarnoosh'
    ).delete()
    Staff.objects.get(
        name='Dorna Dehghani'
    ).delete()
    Staff.objects.get(
        name='Ghazal Shenavar'
    ).delete()
    Staff.objects.get(
        name='Helia Akhtarkavian'
    ).delete()
    Staff.objects.get(
        name='Sabiheh Tajdari'
    ).delete()
    Staff.objects.create(
        name='Sahel Messforoosh'
    ).delete()
    Staff.objects.get(
        name='Esmaeil Pahang'
    ).delete()
    Staff.objects.get(
        name='Hamila Meili'
    ).delete()
    Staff.objects.get(
        name='Mahdieh Ebrahimpoor'
    ).delete()
    Staff.objects.get(
        name='Roya Aghvami'
    ).delete()
    Staff.objects.get(
        name='Sara Zahedi'
    ).delete()
    Staff.objects.get(
        name='Hossein Aghamohammadi'
    ).delete()
    Staff.objects.get(
        name='Vahid Zehtab'
    ).delete()
    Staff.objects.get(
        name='Amirhossein Asem Yousefi'
    ).delete()
    Staff.objects.get(
        name='Alireza Ziaei'
    ).delete()
    Staff.objects.get(
        name='Ehsan Movafagh'
    ).delete()
    Staff.objects.get(
        name='ArshiA Akhavan'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_fill_speakers_data'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
