# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations

def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    Staff.objects.create(
        name='علیرضا ایلامی'
    )
    Staff.objects.create(
        name='مهدی فروردین'
    )
    Staff.objects.create(
        name='حسین فیروز'
    )
    Staff.objects.create(
        name='سپهر امینی افشار'
    )
    Staff.objects.create(
        name='فرزام زهدی نسب'
    )
    Staff.objects.create(
        name='پویا معینی'
    )
    Staff.objects.create(
        name='سید محمدمهدی حاتمی'
    )
    Staff.objects.create(
        name='عمران باتمان غلیچ'
    )
    Staff.objects.create(
        name='احمد سلیمی'
    )
    Staff.objects.create(
        name='علی اصغر قناتی'
    )
    Staff.objects.create(
        name='فاطمه خاشعی'
    )
    Staff.objects.create(
        name='علیرضا تاجمیر ریاحی'
    )
    Staff.objects.create(
        name='محمدمهدی برقی'
    )
    Staff.objects.create(
        name='سید علیرضا هاشمی'
    )
    Staff.objects.create(
        name='امیرحسین هادیان'
    )
    Staff.objects.create(
        name='امیرمحمد ایمانی'
    )
    Staff.objects.create(
        name='سجاد رضوانی'
    )
    Staff.objects.create(
        name='شیما رمدانی'
    )
    Staff.objects.create(
        name='مهدی جلالی'
    )
    Staff.objects.create(
        name='سید علیرضا حسینی'
    )
    Staff.objects.create(
        name='سارا آذرنوش'
    )
    Staff.objects.create(
        name='درنا دهقانی'
    )
    Staff.objects.create(
        name='غزل شناور'
    )
    Staff.objects.create(
        name='هلیا اخترکاویان'
    )
    Staff.objects.create(
        name='صبیحه تاجداری'
    )
    Staff.objects.create(
        name='ساحل مس فروش'
    )
    Staff.objects.create(
        name='اسماعیل پاهنگ'
    )
    Staff.objects.create(
        name='همیلا میلی'
    )
    Staff.objects.create(
        name='مهدیه ابراهیم پور'
    )
    Staff.objects.create(
        name='رویا اقوامی'
    )
    Staff.objects.create(
        name='سارا زاهدی'
    )
    Staff.objects.create(
        name='حسین آقامحمدی'
    )
    Staff.objects.create(
        name='وحید زهتاب'
    )
    Staff.objects.create(
        name='امیرحسین عاصم یوسفی'
    )
    Staff.objects.create(
        name='علیرضا ضیایی'
    )

def rollback(apps, schema_editor):
    Staff = apps.get_model('people', 'Speaker')
    Staff.objects.get(
        name='علیرضا ایلامی'
    ).delete()
    Staff.objects.get(
        name='مهدی فروردین'
    ).delete()
    Staff.objects.get(
        name='حسین فیروز'
    ).delete()
    Staff.objects.get(
        name='سپهر امینی افشار'
    ).delete()
    Staff.objects.get(
        name='فرزام زهدی نسب'
    ).delete()
    Staff.objects.get(
        name='پویا معینی'
    ).delete()
    Staff.objects.get(
        name='سید محمدمهدی حاتمی'
    ).delete()
    Staff.objects.get(
        name='عمران باتمان غلیچ'
    ).delete()
    Staff.objects.get(
        name='احمد سلیمی'
    ).delete()
    Staff.objects.get(
        name='علی اصغر قناتی'
    ).delete()
    Staff.objects.get(
        name='فاطمه خاشعی'
    ).delete()
    Staff.objects.get(
        name='علیرضا تاجمیر ریاحی'
    ).delete()
    Staff.objects.get(
        name='محمدمهدی برقی'
    ).delete()
    Staff.objects.get(
        name='سید علیرضا هاشمی'
    ).delete()
    Staff.objects.get(
        name='امیرحسین هادیان'
    ).delete()
    Staff.objects.get(
        name='امیرمحمد ایمانی'
    ).delete()
    Staff.objects.get(
        name='سجاد رضوانی'
    ).delete()
    Staff.objects.get(
        name='شیما رمدانی'
    ).delete()
    Staff.objects.get(
        name='مهدی جلالی'
    ).delete()
    Staff.objects.get(
        name='سید علیرضا حسینی'
    ).delete()
    Staff.objects.get(
        name='سارا آذرنوش'
    ).delete()
    Staff.objects.get(
        name='درنا دهقانی'
    ).delete()
    Staff.objects.get(
        name='غزل شناور'
    ).delete()
    Staff.objects.get(
        name='هلیا اخترکاویان'
    ).delete()
    Staff.objects.get(
        name='صبیحه تاجداری'
    ).delete()
    Staff.objects.create(
        name='ساحل مس فروش'
    ).delete()
    Staff.objects.get(
        name='اسماعیل پاهنگ'
    ).delete()
    Staff.objects.get(
        name='همیلا میلی'
    ).delete()
    Staff.objects.get(
        name='مهدیه ابراهیم پور'
    ).delete()
    Staff.objects.get(
        name='رویا اقوامی'
    ).delete()
    Staff.objects.get(
        name='سارا زاهدی'
    ).delete()
    Staff.objects.get(
        name='حسین آقامحمدی'
    ).delete()
    Staff.objects.get(
        name='وحید زهتاب'
    ).delete()
    Staff.objects.get(
        name='امیرحسین عاصم یوسفی'
    ).delete()
    Staff.objects.get(
        name='علیرضا ضیایی'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_fill_speakers_data'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
