# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations

def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    teams = apps.get_model('people', 'HoldingTeam')
    teams.objects.create(
        name='content'
    )
    team = teams.objects.get(name='content')
    team.staff.add(
        Staff.objects.get(name='Mehdi Farvardin'),
        Staff.objects.get(name='Hossein Firooz'),
        Staff.objects.get(name='Sepehr Amini Afshar'),
        Staff.objects.get(name='Farzam Zohdinasab'),
        Staff.objects.get(name='Pooya Moeini'),
        Staff.objects.get(name='Seyed Mohammad mehdi Hatami')
    )
    teams.objects.create(
        name='technical'
    )
    team = teams.objects.get(name='technical')
    team.staff.add(
        Staff.objects.get(name='Emran Batman ghelich'),
        Staff.objects.get(name='Ahmad Salimi'),
        Staff.objects.get(name='Ali asghar Ghanati'),
        Staff.objects.get(name='Fateme Khashei'),
        Staff.objects.get(name='Alireza Tajmir riahi'),
        Staff.objects.get(name='Mohammad mehdi Barghi'),
        Staff.objects.get(name='Seyed Alireza Hashemi'),
    )
    teams.objects.create(
        name='network'
    )
    team = teams.objects.get(name='network')
    team.staff.add(
        Staff.objects.get(name='Amirhossein Hadian'),
        Staff.objects.get(name='Amirmohammad Imani'),
        Staff.objects.get(name='Sajjad Rezvani'),
        Staff.objects.get(name='Shima Ramadani'),
        Staff.objects.get(name='Mehdi Jalali'),
        Staff.objects.get(name='Sara Azarnoosh')
    )
    teams.objects.create(
        name='branding'
    )
    team = teams.objects.get(name='branding')
    team.staff.add(
        Staff.objects.get(name='Seyed Alireza Hosseini')
    )
    teams.objects.create(
        name='social'
    )
    team = teams.objects.get(name='social')
    team.staff.add(
        Staff.objects.get(name='Sara Azarnoosh'),
        Staff.objects.get(name='Dorna Dehghani'),
        Staff.objects.get(name='Ghazal Shenavar'),
        Staff.objects.get(name='Helia Akhtarkavian'),
        Staff.objects.get(name='Sabiheh Tajdari'),
        Staff.objects.get(name='Sahel Messforoosh'),
        Staff.objects.get(name='Esmaeil Pahang')
    )
    teams.objects.create(
        name='media'
    )
    team = teams.objects.get(name='media')
    team.staff.add(
        Staff.objects.get(name='Hamila Meili'),
        Staff.objects.get(name='Mahdieh Ebrahimpoor'),
        Staff.objects.get(name='Roya Aghvami'),
        Staff.objects.get(name='Sara Zahedi'),
        Staff.objects.get(name='Hossein Aghamohammadi')
    )
    teams.objects.create(
        name='presentation management'
    )
    team = teams.objects.get(name='presentation management')
    team.staff.add(
        Staff.objects.get(name='Alireza Ziaei'),
        Staff.objects.get(name='Amirhossein Asem Yousefi'),
        Staff.objects.get(name='Vahid Zehtab'),
        Staff.objects.get(name='Sajjad Rezvani')
    )


def rollback(apps, schema_editor):
    teams.objects.get(name='content').delete()
    teams.objects.get(name='technical').delete()
    teams.objects.get(name='network').delete()
    teams.objects.get(name='branding').delete()
    teams.objects.get(name='social').delete()
    teams.objects.get(name='media').delete()
    teams.objects.get(name='presentation management').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_fill_staff_data'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
