# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations
from people.models import Staff
from django.contrib.contenttypes.models import ContentType


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')

    ctype = ContentType.objects.get_for_model(Staff)
    Staff.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=ctype)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_fill_holding_team_data'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
