# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def forwards(apps, schema_editor):
    Speaker = apps.get_model('people', 'Speaker')

    ctype = ContentType.objects.get_for_model(Speaker)
    Speaker.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=ctype)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_add_ctype_to_staff'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
