# Generated by Django 3.1.3 on 2020-12-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_add_ctype_to_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technicalexpert',
            name='picture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
