# Generated by Django 3.1.3 on 2020-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_fill_seminar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingteam',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
