# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations

def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Speakers.objects.create(
        name='Mostafa Rezazad',
        degree='Ph.D.',
        place='senior researcher at the Institute for Research in Fundamental Sciences',
        bio='Dr Mostafa Rezazad Received his Ph.D. from the National University of Singapore. Then he joined the CiSDeM group at SUTD university to work on applying AI in the Cybersecurity domain. Now, he is a senior researcher at the Institute for Research in Fundamental Sciences where he is pursuing his research in various directions in the Networking field.'
    )
    Speakers.objects.create(
        name='Mehraveh Salehi',
        degree='Ph.D.',
        place='Chief Experience Officer at Summary Analytics Inc., Seattle, WA',
        bio='Mehraveh Salehi is the Chief Experience Officer at Summary Analytics Inc., Seattle, WA. She received her Ph.D. in Electrical Engineering from Yale University (2019), and her B.Sc. from Sharif University of Technology (2014).  Her research lies at the intersection of artificial and natural intelligence with a focus on submodularity and its applications in the human brain. She is the recipient of numerous awards including 1st place in the inter-ivy 3-Minute Thesis (3MT) Competition at the United Nations (2019), the Young Scientist Award at MICCAI (2017), and Yale Advanced Graduate Leadership Program (AGLP) fellowship (2016).'
    )
    Speakers.objects.create(
        name='Mohammad Haft-Javaheiran',
        degree='Ph.D.',
        place='Bullock Postdoctoral Research Fellow at Wellman Center, Harvard Medical School and MIT Computer Science & Artificial Intelligence Lab',
        bio='Mohammad Haft-Javaherian is Bullock Postdoctoral Research Fellow at Wellman Center, Harvard Medical School and MIT Computer Science & Artificial Intelligence Lab, where he works with Brett Bouma and Polina Golland. He received his Ph.D. in Biomedical engineering from Cornell University, where he worked with Nozomi Nishimura and Chris Schaffer and had close collaboration with Mert Sabuncu.'
    )
    Speakers.objects.create(
        name='Mohamad Kazem Shirani Faradonbeh',
        degree='Ph.D.',
        place='assistant professor at the University of Georgia.',
        bio='received the Ph.D. degree in Statistics from the University of Michigan in 2017, and the B.Sc. degree in Electrical Engineering from Sharif University of Technology in 2012. He is currently an assistant professor of data science in the Department of Statistics at the University of Georgia.'
    )
    Speakers.objects.create(
        name='Mohammad Dehghani',
        degree='Master',
        place='Tarbiat Modares University',
    )
    Speakers.objects.create(
        name='Mohammad Fazeli',
        degree='Master',
        place='Sharif University of Technology',
    )
    Speakers.objects.create(
        name='Mohammad Heydari',
        degree='Master',
        place='Tarbiat Modares University',
    )
    Speakers.objects.create(
        name='Maryam Sadat Eslami',
        degree='Master',
        place='Iran university of science and technology',
    )
    Speakers.objects.create(
        name='Mohammad Mahdi Samiei',
        degree='Ph.D.',
        place='Sharif University of Technology',
    )
    Speakers.objects.create(
        name='Mohammadhossein Bahari',
        degree='Master',
        place='EPFL',
    )
    

def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Speakers.objects.filter(name__in=[
        'Mostafa Rezazad',
        'Mehraveh Salehi',
        'Mohammad Haft-Javaheiran',
        'Mohamad Kazem Shirani Faradonbeh',
        'Mohammad Dehghani',
        'Mohammad Fazeli',
        'Mohammad Heydari',
        'Maryam Sadat Eslami',
        'Mohammad Mahdi Samiei',
        'Mohammadhossein Bahari',
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_fill_staff_data'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
