# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    HoldingTeam = apps.get_model('people', 'HoldingTeam')
    WSS = apps.get_model('WSS', 'WSS')

    wss = WSS.objects.get(year=2020)

    HoldingTeam.objects.filter(wss=wss, name='Network').update(name='Networking')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_update_holding_team_orders'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
