# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def forwards(apps, schema_editor):
    HoldingTeam = apps.get_model('people', 'HoldingTeam')
    WSS = apps.get_model('WSS', 'WSS')

    wss = WSS.objects.get(year=2020)
    HoldingTeam.objects.filter(wss=wss).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_rename_holding_team_2020'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
