# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speaker = apps.get_model('people', 'Speaker')

    Speaker.objects.filter(name='Shahram Ghandeharizadeh').update(place='faculty member at the University of Southern California')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_rename_holding_team'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
