# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    WSS = apps.get_model('WSS', 'WSS')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')

    # There's two Fatemeh Khashei because of a bug in previous migrations. So, one of them will be removed.
    Staff.objects.filter(name='Fatemeh Khashei').first().delete()

    teams_staff = {
        'Manager & Director': ['Alireza Ilami'],
        'Scientific Secretary': ['Shayan Oveis gharan'],
        'Content': ['Mahdi Farvardin', 'Hossein Firooz', 'Sepehr Amini Afshar', 'Farzam Zohdinasab', 'Pooya Moeini', 'Seyed Mohammad mehdi Hatami'],
        'Technical': ['Emran Batmanghelich', 'Ahmad Salimi', 'Ali asghar Ghanati', 'Fatemeh Khashei', 'Alireza Tajmir riahi', 'Seyed Alireza Hashemi', 'Mohammad mehdi Barghi'],
        'Networking': ['Amirhossein Hadian', 'Shima Ramadani', 'Sara Azarnoosh', 'Ehsan Movafagh', 'Fatemeh Asgari', 'Sajjad Rezvani', 'Amirmohammad Imani', 'Mehdi Jalali'],
        'Branding': ['Seyed Alireza Hosseini'],
        'Social': ['Sara Azarnoosh', 'Dorna Dehghani', 'Ghazal Shenavar', 'Helia Akhtarkavian', 'Sabiheh Tajdari', 'Sahel Messforoosh', 'Esmaeil Pahang'],
        'Media': ['Hamila Meili', 'Mahdieh Ebrahimpoor', 'Roya Ghavami', 'Sara Zahedi', 'Mohammad mehdi Barghi'],
        'Presentation Management': ['Alireza Ziaei', 'Sajjad Rezvani', 'Vahid Zehtab', 'Amirhossein Asem Yousefi'],
    }

    wss = WSS.objects.get(year=2020)

    i = 1
    for team_name in teams_staff:
        team = HoldingTeam.objects.create(wss=wss, name=team_name, order=i)
        team.staff.set(Staff.objects.filter(name__in=teams_staff[team_name]).order_by('id'))
        i += 1


def rollback(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')

    wss = WSS.objects.get(year=2020)

    team_names = ['Content', 'Technical', 'Networking', 'Branding', 'Social', 'Media', 'Presentation Management']
    HoldingTeam.objects.filter(wss=wss, name__in=team_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_remove_2020_holding_teams'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
