# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')

    teams_staff = {
        'Manager & Director': ['Alireza Ilami'],
        'Scientific Secretary': ['Shayan Oveis gharan'],
        'Content': ['Mahdi Farvardin', 'Hossein Firooz', 'Sepehr Amini Afshar', 'Farzam Zohdinasab', 'Pooya Moeini', 'Seyed Mohammad mehdi Hatami'],
        'Networking': ['Amirhossein Hadian', 'Shima Ramadani', 'Sara Azarnoosh', 'Ehsan Movafagh', 'Fatemeh Asgari', 'Sajjad Rezvani', 'Amirmohammad Imani', 'Mehdi Jalali'],
        'Branding': ['Seyed Alireza Hosseini'],
        'Social': ['Sara Azarnoosh', 'Dorna Dehghani', 'Ghazal Shenavar', 'Helia Akhtarkavian', 'Sabiheh Tajdari', 'Sahel Messforoosh', 'Esmaeil Pahang'],
        'Media': ['Hamila Meili', 'Mahdieh Ebrahimpoor', 'Roya Ghavami', 'Sara Zahedi', 'Mohammad mehdi Barghi'],
        'Technical': ['Emran Batmanghelich', 'Ahmad Salimi', 'Ali asghar Ghanati', 'Fatemeh Khashei', 'Alireza Tajmir riahi', 'Seyed Alireza Hashemi', 'Mohammad mehdi Barghi'],
        'Presentation Management': ['Alireza Ziaei', 'Sajjad Rezvani', 'Vahid Zehtab', 'Amirhossein Asem Yousefi'],
    }

    for team_name in teams_staff:
        i = 1
        if team_name == 'Social':
            i = 3
        for name in teams_staff[team_name]:
            Staff.objects.filter(name=name).update(order=i)
            i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_rename_a_2020_staff'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
