# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')

    ctype = ContentType.objects.get_for_model(Staff)

    Staff.objects.get(name='Mohammad mehdi Barghi').delete()

    id = Staff.objects.all().last().id

    staff = Staff.objects.create(
        id=id + 1,
        name='Mohammad mahdi Barghi',
        picture='media/2020/staff/Mohammad-mehdi-Barghi.jpg',
        polymorphic_ctype=ctype
    )

    team = HoldingTeam.objects.get(name='Technical')
    team.staff.add(staff)
    team.save()

    team = HoldingTeam.objects.get(name='Media')
    team.staff.add(staff)
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_rename_a_2020_staff'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
