# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    
    Staff.objects.filter(holding_teams__wss__year=2020, name='Shayan Oveis gharan').update(name='Shayan Oveis Gharan')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Sabiheh Tajdari').update(name='Sabihe Tajdari')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Alireza Tajmir riahi').update(name='Alireza Tajmir Riahi')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Seyed Mohammad mehdi Hatami').update(name='Seyed Mohammad Mehdi Hatami')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Sahel Messforoosh').update(name='Sahel Mesforoosh')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Mehdi Jalali').update(name='Mahdi Jalali')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Mohammad mehdi Barghi').update(name='Mohammad Mehdi Barghi')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Ali asghar Ghanati').update(name='Ali Asghar Ghanati')

def rollback(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    
    Staff.objects.filter(holding_teams__wss__year=2020, name='Shayan Oveis Gharan').update(name='Shayan Oveis gharan')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Sabihe Tajdari').update(name='Sabiheh Tajdari')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Alireza Tajmir Riahi').update(name='Alireza Tajmir Riahi')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Seyed Mohammad Mehdi Hatami').update(name='Seyed Mohammad mehdi Hatami')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Sahel Mesforoosh').update(name='Sahel Messforoosh')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Mahdi Jalali').update(name='Mehdi Jalali')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Mohammad Mehdi Barghi').update(name='Mohammad mehdi Barghi')
    Staff.objects.filter(holding_teams__wss__year=2020, name='Ali Asghar Ghanati').update(name='Ali asghar Ghanati')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_update_staff_orders'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
