# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations
    

def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Speakers.objects.filter(name__in=[
        'Mohammad Haft-Javaheiran',
    ]).update(name='Mohammad Haft-Javaherian')

class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_add_new_speakers_2020'),
        ('events', '0008_fill_more_seminars_2020')
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
