# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Hamed Haddadi',
        defaults={
            'picture': 'media/7th/speakers/Hamed-Haddadi.jpg',
            'degree': 'PhD',
            'place': 'Imperial College London',
            'polymorphic_ctype': ctype,
            'bio': '''Hamed is a Reader in Human-Centred Systems and the Director of Postgraduate Studies at the Dyson School of Design Engineering at The Faculty of Engineering, Imperial College London. He serves as a Security Science Fellow of the Institute for Security Science and Technology, leads the Systems and Algorithms Laboratory, and is an Academic Fellow of the Data Science Institute. . In his industrial role, he is a Visiting Professor and the Chief Scientist at Brave Software where he works on developing privacy-preserving analytics protocols. He is interested in User-Centred Systems, IoT, Applied Machine Learning, and Data Security & Privacy. He enjoys designing and building systems that enable better use of our digital footprint, while respecting users' privacy.
He studied for BEng/MSc/PhD at University College London and the University of Cambridge. He was a postdoctoral researcher at Max Planck Institute for Software Systems in Germany, and a postdoctoral research fellow at Department of Pharmacology, University of Cambridge and The Royal Veterinary College, University of London, followed by few years as a Lecturer and consequently Senior Lecturer in Digital Media at Queen Mary University of London. He has spent time working and collaborating with Brave Software, Intel Research, Microsoft Research, AT&T Research, Telefonica, and Sony Europe. When not in the lab, he prefers to be on a ski slope or in a kayak.'''
        })
    Speakers.objects.get_or_create(
        name='Pooya Hatami',
        defaults={
            'picture': 'media/7th/speakers/Pooya-Hatami.jpg',
            'degree': 'PhD, University of Chicago',
            'place': 'CSE, Ohio State University',
            'polymorphic_ctype': ctype,
            'bio': '''Pooya Hatami is an assistant professor in the CSE department at the Ohio State University. His research interests are broadly in theoretical computer science, on topics such as randomness and pseudorandomness, communication complexity, analysis of Boolean functions, and additive combinatorics. He obtained his Ph.D. from the University of Chicago, where he was advised by Alexander Razborov and Madhur Tulsiani. Before joining OSU, he spent a few years as a postdoctoral researcher in the Institute for Advanced Study, DIMACS, and the University of Texas at Austin.''',
        })
    Speakers.objects.get_or_create(
        name='Amir Moradi',
        defaults={
            'picture': 'media/7th/speakers/Amir-Moradi.png',
            'degree': 'Prof.',
            'place': 'University of Cologne, Germany',
            'polymorphic_ctype': ctype,
            'bio': '''Amir Moradi received the M.Sc. and Ph.D. degrees in computer engineering from Sharif University of Technology, Tehran, Iran, in 2004 and 2008 respectively. Afterwards, till 2015 he worked as a Post-Doctoral researcher at the chair for Embedded Security, Ruhr University Bochum, Germany. In 2016 after obtaining the Habilitation degree, he joined the faculty of Electrical Engineering and Information Technology at Ruhr University Bochum, and afterwards has become a professor at the same faculty. Since October 2021 he is a professor for IT Security at the Institute for Computer Science at the University of Cologne, Germany. His current research interests include physical security of embedded systems, passive and active physical attacks, and the corresponding countermeasures. To date, he has published over 140 peer-reviewed journal articles and conference papers, in both destructive and constructive aspects of side-channel analysis. He also served as Program Committee Member (and the Chair) of several security- and cryptography-related conferences and workshops.''',
        })
    Speakers.objects.get_or_create(
        name='Mohammad Hajiabadi',
        defaults={
            'picture': 'media/7th/speakers/Mohammad-Hajiabadi.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, University of Waterloo',
            'polymorphic_ctype': ctype,
            'bio': '''Mohammad Hajiabadi is an Assistant Professor of Computer Science at the University of Waterloo. Prior to that, he was an Assistant Professor in Computer Science at Pennsylvania State University. He was a postdoctoral researcher at UC Berkeley and the University of Virginia for three years. He received his PhD in Computer Science from the University of Victoria. His main research interests are in Foundations of Cryptography, and Theoretical Computer Science.''',
        })
    Speakers.objects.get_or_create(
        name='Soheil Abbasloo',
        defaults={
            'picture': 'media/7th/speakers/Soheil-Abbasloo.jpg',
            'degree': 'PhD',
            'place': 'University of Toronto',
            'polymorphic_ctype': ctype,
            'bio': '''Soheil Abbasloo received a Ph.D. degree in electrical engineering from the New York University in 2020. Before his studies at NYU, he worked as a Network Protocol Designer and a Software Engineer for more than four years.  He is currently a postdoctoral fellow at the department of computer science, University of Toronto. His research is centered around congestion control, ultra-low latency networks, machine learning-assisted network design, scheduling and resource management, datacenter networks, and cellular networks.''',
        })
    Speakers.objects.get_or_create(
        name='Amir Zamir',
        defaults={
            'picture': 'media/7th/speakers/Amir-Zamir.jpg',
            'degree': 'PhD',
            'place': 'EPFL',
            'polymorphic_ctype': ctype,
            'bio': '''I am a tenure-track Assistant Professor of Computer Science at the Swiss Federal Institute of Technology (EPFL). Prior to EPFL, I spent time at UC Berkeley, Stanford, and UCF where I had the opportunity of working with Jitendra Malik, Silvio Savarese, Mubarak Shah, Rahul Sukthankar, and Leonidas Guibas. I am also the lead CV/ML scientist of Aurora Solar since 2015.''',
        })
    Speakers.objects.get_or_create(
        name='Mahdi Cheraghchi',
        defaults={
            'picture': 'media/7th/speakers/Mahdi-Cheraghchi.jpg',
            'degree': 'PhD',
            'place': 'University of Michigan',
            'polymorphic_ctype': ctype,
            'bio': '''I'm an Assistant Professor of Computer Science and Engineering at the EECS Department of the University of Michigan, Ann Arbor. Previously, I have been on the faculty of the Department of Computing, Imperial College London (where I maintain an Honorary Senior Lecturer position), a Qualcomm Research Fellow at the Simons Institute for the Theory of Computing of U.C. Berkeley and post-doctoral scholar at the MIT Computer Science and Artificial Intelligence Lab (hosted by Piotr Indyk), Computer Science Department of the Carnegie Mellon University (hosted by Venkatesan Guruswami) and the University of Texas at Austin (hosted by David Zuckerman).''',
        })
    Speakers.objects.get_or_create(
        name='Masoumeh Ebrahimi',
        defaults={
            'picture': 'media/7th/speakers/Masoumeh-Ebrahimi.jpg',
            'degree': 'PhD',
            'place': 'KTH Royal Institute of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''I am an Associate Professor (docent) at KTH. I am also an Adjunct Professor at the University of Turku, Finland. I received my Ph.D. with honors from the University of Turku, Finland in 2013. I have also received MBA jointly from Turku School of Economics and the European Institute of Innovation & Technology (EIT) ICT Labs. I joined KTH Royal Institute of Technology, Sweden as a Marie-Curie Postdoctoral fellow in 2014. Currently, I am leading several projects at KTH and (co) supervising several M.Sc. and Ph.D. students. My main areas of interest include Systems-on-Chip, Interconnection Netwroks, Near-Memory Processing, and Machine Learning Accelerators.''',
        })
    Speakers.objects.get_or_create(
        name='Amir Shaikhha',
        defaults={
            'picture': 'media/7th/speakers/Amir-Shaikhha.jpg',
            'degree': 'PhD',
            'place': 'University of Edinburgh',
            'polymorphic_ctype': ctype,
            'bio': '''Amir is an Assistant Professor (Lecturer) in the School of Informatics at the University of Edinburgh. His research focuses on the design and implementation of data-analytics systems by using techniques from the databases, programming languages, compilers, and machine learning communities. Prior to that, he was a Departmental Lecturer at Oxford. He earned his Ph.D. from EPFL in 2018, for which he was awarded a Google Ph.D. Fellowship in structured data analysis, as well as a Ph.D. thesis distinction award.''',
        })


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Hamed Haddadi', 'Pooya Hatami', 'Amir Moradi', 'Mohammad Hajiabadi',
             'Soheil Abbasloo', 'Amir Zamir', 'Mahdi Cheraghchi', 'Masoumeh Ebrahimi', 'Amir Shaikhha', ]
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_fill_2019_speakers_data'),
        ('WSS', '0019_add_7th_WSS'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
