# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Hamed Haddadi',
        defaults={
            'picture': 'media/7th/speakers/Hamed-Haddadi.jpg',
            'degree': 'PhD',
            'place': 'Reader (Associate Professor), Imperial College London',
            'polymorphic_ctype': ctype,
            'bio': '''Hamed is a Reader in Human-Centred Systems and the Director of Postgraduate Studies at the Dyson School of Design Engineering at The Faculty of Engineering, Imperial College London. He serves as a Security Science Fellow of the Institute for Security Science and Technology, leads the Systems and Algorithms Laboratory, and is an Academic Fellow of the Data Science Institute. . In his industrial role, he is a Visiting Professor and the Chief Scientist at Brave Software where he works on developing privacy-preserving analytics protocols. He is interested in User-Centred Systems, IoT, Applied Machine Learning, and Data Security & Privacy. He enjoys designing and building systems that enable better use of our digital footprint, while respecting users' privacy.
He studied for BEng/MSc/PhD at University College London and the University of Cambridge. He was a postdoctoral researcher at Max Planck Institute for Software Systems in Germany, and a postdoctoral research fellow at Department of Pharmacology, University of Cambridge and The Royal Veterinary College, University of London, followed by few years as a Lecturer and consequently Senior Lecturer in Digital Media at Queen Mary University of London. He has spent time working and collaborating with Brave Software, Intel Research, Microsoft Research, AT&T Research, Telefonica, and Sony Europe. When not in the lab, he prefers to be on a ski slope or in a kayak.'''
        })
        
    Speakers.objects.filter(name='Hamed Haddadi').update(
            picture='media/7th/speakers/Hamed-Haddadi.jpg',
            degree='PhD',
            place='Reader (Associate Professor), Imperial College London',
            polymorphic_ctype=ctype,
            bio='''Hamed is a Reader in Human-Centred Systems and the Director of Postgraduate Studies at the Dyson School of Design Engineering at The Faculty of Engineering, Imperial College London. He serves as a Security Science Fellow of the Institute for Security Science and Technology, leads the Systems and Algorithms Laboratory, and is an Academic Fellow of the Data Science Institute. . In his industrial role, he is a Visiting Professor and the Chief Scientist at Brave Software where he works on developing privacy-preserving analytics protocols. He is interested in User-Centred Systems, IoT, Applied Machine Learning, and Data Security & Privacy. He enjoys designing and building systems that enable better use of our digital footprint, while respecting users' privacy.
He studied for BEng/MSc/PhD at University College London and the University of Cambridge. He was a postdoctoral researcher at Max Planck Institute for Software Systems in Germany, and a postdoctoral research fellow at Department of Pharmacology, University of Cambridge and The Royal Veterinary College, University of London, followed by few years as a Lecturer and consequently Senior Lecturer in Digital Media at Queen Mary University of London. He has spent time working and collaborating with Brave Software, Intel Research, Microsoft Research, AT&T Research, Telefonica, and Sony Europe. When not in the lab, he prefers to be on a ski slope or in a kayak.''')
    
    Speakers.objects.get_or_create(
        name='Pooya Hatami',
        defaults={
            'picture': 'media/7th/speakers/Pooya-Hatami.jpg',
            'degree': 'PhD, University of Chicago',
            'place': 'Assistant Professor, CSE, Ohio State University',
            'polymorphic_ctype': ctype,
            'bio': '''Pooya Hatami is an assistant professor in the CSE department at the Ohio State University. His research interests are broadly in theoretical computer science, on topics such as randomness and pseudorandomness, communication complexity, analysis of Boolean functions, and additive combinatorics. He obtained his Ph.D. from the University of Chicago, where he was advised by Alexander Razborov and Madhur Tulsiani. Before joining OSU, he spent a few years as a postdoctoral researcher in the Institute for Advanced Study, DIMACS, and the University of Texas at Austin.''',
        })
        
    Speakers.objects.filter(name='Pooya Hatami').update(
            picture='media/7th/speakers/Pooya-Hatami.jpg',
            degree='PhD, University of Chicago',
            place='Assistant Professor, CSE, Ohio State University',
            polymorphic_ctype=ctype,
            bio='''Pooya Hatami is an assistant professor in the CSE department at the Ohio State University. His research interests are broadly in theoretical computer science, on topics such as randomness and pseudorandomness, communication complexity, analysis of Boolean functions, and additive combinatorics. He obtained his Ph.D. from the University of Chicago, where he was advised by Alexander Razborov and Madhur Tulsiani. Before joining OSU, he spent a few years as a postdoctoral researcher in the Institute for Advanced Study, DIMACS, and the University of Texas at Austin.''')

    Speakers.objects.get_or_create(
        name='Amir Moradi',
        defaults={
            'picture': 'media/7th/speakers/Amir-Moradi.png',
            'degree': 'Prof.',
            'place': 'Professor, University of Cologne, Germany',
            'polymorphic_ctype': ctype,
            'bio': '''Amir Moradi received the M.Sc. and Ph.D. degrees in computer engineering from Sharif University of Technology, Tehran, Iran, in 2004 and 2008 respectively. Afterwards, till 2015 he worked as a Post-Doctoral researcher at the chair for Embedded Security, Ruhr University Bochum, Germany. In 2016 after obtaining the Habilitation degree, he joined the faculty of Electrical Engineering and Information Technology at Ruhr University Bochum, and afterwards has become a professor at the same faculty. Since October 2021 he is a professor for IT Security at the Institute for Computer Science at the University of Cologne, Germany. His current research interests include physical security of embedded systems, passive and active physical attacks, and the corresponding countermeasures. To date, he has published over 140 peer-reviewed journal articles and conference papers, in both destructive and constructive aspects of side-channel analysis. He also served as Program Committee Member (and the Chair) of several security- and cryptography-related conferences and workshops.''',
        })
        
    Speakers.objects.filter(name='Amir Moradi').update(
            picture='media/7th/speakers/Amir-Moradi.png',
            degree='Prof.',
            place='Professor, University of Cologne, Germany',
            polymorphic_ctype=ctype,
            bio='''Amir Moradi received the M.Sc. and Ph.D. degrees in computer engineering from Sharif University of Technology, Tehran, Iran, in 2004 and 2008 respectively. Afterwards, till 2015 he worked as a Post-Doctoral researcher at the chair for Embedded Security, Ruhr University Bochum, Germany. In 2016 after obtaining the Habilitation degree, he joined the faculty of Electrical Engineering and Information Technology at Ruhr University Bochum, and afterwards has become a professor at the same faculty. Since October 2021 he is a professor for IT Security at the Institute for Computer Science at the University of Cologne, Germany. His current research interests include physical security of embedded systems, passive and active physical attacks, and the corresponding countermeasures. To date, he has published over 140 peer-reviewed journal articles and conference papers, in both destructive and constructive aspects of side-channel analysis. He also served as Program Committee Member (and the Chair) of several security- and cryptography-related conferences and workshops.''')

    Speakers.objects.get_or_create(
        name='Mohammad Hajiabadi',
        defaults={
            'picture': 'media/7th/speakers/Mohammad-Hajiabadi.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, University of Waterloo',
            'polymorphic_ctype': ctype,
            'bio': '''Mohammad Hajiabadi is an Assistant Professor of Computer Science at the University of Waterloo. Prior to that, he was an Assistant Professor in Computer Science at Pennsylvania State University. He was a postdoctoral researcher at UC Berkeley and the University of Virginia for three years. He received his PhD in Computer Science from the University of Victoria. His main research interests are in Foundations of Cryptography, and Theoretical Computer Science.''',
        })
        
    Speakers.objects.filter(name='Mohammad Hajiabadi').update(
            picture='media/7th/speakers/Mohammad-Hajiabadi.jpg',
            degree='PhD',
            place='Assistant Professor, University of Waterloo',
            polymorphic_ctype=ctype,
            bio='''Mohammad Hajiabadi is an Assistant Professor of Computer Science at the University of Waterloo. Prior to that, he was an Assistant Professor in Computer Science at Pennsylvania State University. He was a postdoctoral researcher at UC Berkeley and the University of Virginia for three years. He received his PhD in Computer Science from the University of Victoria. His main research interests are in Foundations of Cryptography, and Theoretical Computer Science.''')

    Speakers.objects.get_or_create(
        name='Soheil Abbasloo',
        defaults={
            'picture': 'media/7th/speakers/Soheil-Abbasloo.jpg',
            'degree': 'PhD',
            'place': 'Postdoctoral Fellow, University of Toronto',
            'polymorphic_ctype': ctype,
            'bio': '''Soheil Abbasloo received a Ph.D. degree in electrical engineering from the New York University in 2020. Before his studies at NYU, he worked as a Network Protocol Designer and a Software Engineer for more than four years.  He is currently a postdoctoral fellow at the department of computer science, University of Toronto. His research is centered around congestion control, ultra-low latency networks, machine learning-assisted network design, scheduling and resource management, datacenter networks, and cellular networks.''',
        })
        
    Speakers.objects.filter(name='Soheil Abbasloo').update(
            picture='media/7th/speakers/Soheil-Abbasloo.jpg',
            degree='PhD',
            place='Postdoctoral Fellow, University of Toronto',
            polymorphic_ctype=ctype,
            bio='''Soheil Abbasloo received a Ph.D. degree in electrical engineering from the New York University in 2020. Before his studies at NYU, he worked as a Network Protocol Designer and a Software Engineer for more than four years.  He is currently a postdoctoral fellow at the department of computer science, University of Toronto. His research is centered around congestion control, ultra-low latency networks, machine learning-assisted network design, scheduling and resource management, datacenter networks, and cellular networks.''')

    Speakers.objects.get_or_create(
        name='Amir Zamir',
        defaults={
            'picture': 'media/7th/speakers/Amir-Zamir.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, EPFL',
            'polymorphic_ctype': ctype,
            'bio': '''I am a tenure-track Assistant Professor of Computer Science at the Swiss Federal Institute of Technology (EPFL). Prior to EPFL, I spent time at UC Berkeley, Stanford, and UCF where I had the opportunity of working with Jitendra Malik, Silvio Savarese, Mubarak Shah, Rahul Sukthankar, and Leonidas Guibas. I am also the lead CV/ML scientist of Aurora Solar since 2015.''',
        })
        
    Speakers.objects.filter(name='Amir Zamir').update(
            picture='media/7th/speakers/Amir-Zamir.jpg',
            degree='PhD',
            place='Assistant Professor, EPFL',
            polymorphic_ctype=ctype,
            bio='''I am a tenure-track Assistant Professor of Computer Science at the Swiss Federal Institute of Technology (EPFL). Prior to EPFL, I spent time at UC Berkeley, Stanford, and UCF where I had the opportunity of working with Jitendra Malik, Silvio Savarese, Mubarak Shah, Rahul Sukthankar, and Leonidas Guibas. I am also the lead CV/ML scientist of Aurora Solar since 2015.''')

    Speakers.objects.get_or_create(
        name='Mahdi Cheraghchi',
        defaults={
            'picture': 'media/7th/speakers/Mahdi-Cheraghchi.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, University of Michigan',
            'polymorphic_ctype': ctype,
            'bio': '''I'm an Assistant Professor of Computer Science and Engineering at the EECS Department of the University of Michigan, Ann Arbor. Previously, I have been on the faculty of the Department of Computing, Imperial College London (where I maintain an Honorary Senior Lecturer position), a Qualcomm Research Fellow at the Simons Institute for the Theory of Computing of U.C. Berkeley and post-doctoral scholar at the MIT Computer Science and Artificial Intelligence Lab (hosted by Piotr Indyk), Computer Science Department of the Carnegie Mellon University (hosted by Venkatesan Guruswami) and the University of Texas at Austin (hosted by David Zuckerman).''',
        })
        
    Speakers.objects.filter(name='Mahdi Cheraghchi').update(
            picture='media/7th/speakers/Mahdi-Cheraghchi.jpg',
            degree='PhD',
            place='Assistant Professor, University of Michigan',
            polymorphic_ctype=ctype,
            bio='''I'm an Assistant Professor of Computer Science and Engineering at the EECS Department of the University of Michigan, Ann Arbor. Previously, I have been on the faculty of the Department of Computing, Imperial College London (where I maintain an Honorary Senior Lecturer position), a Qualcomm Research Fellow at the Simons Institute for the Theory of Computing of U.C. Berkeley and post-doctoral scholar at the MIT Computer Science and Artificial Intelligence Lab (hosted by Piotr Indyk), Computer Science Department of the Carnegie Mellon University (hosted by Venkatesan Guruswami) and the University of Texas at Austin (hosted by David Zuckerman).''')

    Speakers.objects.get_or_create(
        name='Masoumeh Ebrahimi',
        defaults={
            'picture': 'media/7th/speakers/Masoumeh-Ebrahimi.jpg',
            'degree': 'PhD',
            'place': 'Associate Professor, KTH Royal Institute of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''I am an Associate Professor (docent) at KTH. I am also an Adjunct Professor at the University of Turku, Finland. I received my Ph.D. with honors from the University of Turku, Finland in 2013. I have also received MBA jointly from Turku School of Economics and the European Institute of Innovation & Technology (EIT) ICT Labs. I joined KTH Royal Institute of Technology, Sweden as a Marie-Curie Postdoctoral fellow in 2014. Currently, I am leading several projects at KTH and (co) supervising several M.Sc. and Ph.D. students. My main areas of interest include Systems-on-Chip, Interconnection Netwroks, Near-Memory Processing, and Machine Learning Accelerators.''',
        })
        
    Speakers.objects.filter(name='Masoumeh Ebrahimi').update(
            picture='media/7th/speakers/Masoumeh-Ebrahimi.jpg',
            degree='PhD',
            place='Associate Professor, KTH Royal Institute of Technology',
            polymorphic_ctype=ctype,
            bio='''I am an Associate Professor (docent) at KTH. I am also an Adjunct Professor at the University of Turku, Finland. I received my Ph.D. with honors from the University of Turku, Finland in 2013. I have also received MBA jointly from Turku School of Economics and the European Institute of Innovation & Technology (EIT) ICT Labs. I joined KTH Royal Institute of Technology, Sweden as a Marie-Curie Postdoctoral fellow in 2014. Currently, I am leading several projects at KTH and (co) supervising several M.Sc. and Ph.D. students. My main areas of interest include Systems-on-Chip, Interconnection Netwroks, Near-Memory Processing, and Machine Learning Accelerators.''')

    Speakers.objects.get_or_create(
        name='Amir Shaikhha',
        defaults={
            'picture': 'media/7th/speakers/Amir-Shaikhha.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, University of Edinburgh',
            'polymorphic_ctype': ctype,
            'bio': '''Amir is an Assistant Professor (Lecturer) in the School of Informatics at the University of Edinburgh. His research focuses on the design and implementation of data-analytics systems by using techniques from the databases, programming languages, compilers, and machine learning communities. Prior to that, he was a Departmental Lecturer at Oxford. He earned his Ph.D. from EPFL in 2018, for which he was awarded a Google Ph.D. Fellowship in structured data analysis, as well as a Ph.D. thesis distinction award.''',
        })
        
    Speakers.objects.filter(name='Amir Shaikhha').update(
            picture='media/7th/speakers/Amir-Shaikhha.jpg',
            degree='PhD',
            place='Assistant Professor, University of Edinburgh',
            polymorphic_ctype=ctype,
            bio='''Amir is an Assistant Professor (Lecturer) in the School of Informatics at the University of Edinburgh. His research focuses on the design and implementation of data-analytics systems by using techniques from the databases, programming languages, compilers, and machine learning communities. Prior to that, he was a Departmental Lecturer at Oxford. He earned his Ph.D. from EPFL in 2018, for which he was awarded a Google Ph.D. Fellowship in structured data analysis, as well as a Ph.D. thesis distinction award.''')

    Speakers.objects.get_or_create(
        name='Behzad Salami',
        defaults={
            'picture': 'media/7th/speakers/Behzad-Salami.png',
            'degree': 'PhD',
            'place': 'Senior Researcher, ETH and BSC',
            'polymorphic_ctype': ctype,
            'bio': '''Behzad Salami received the Ph.D. degree (Hons.) in Computer Architecture from the Universitat Politècnica de Catalunya  (UPC) in 2018, followed by a post-doc in the Computer Science department of Barcelona Supercomputing Centre (BSC). He is currently collaborating with the SAFARI Research Group as an affiliated researcher. He had short research visits at the University of Manchester (UK) and the Institute for Research in Fundamental Sciences (Iran). He has collaborated with academia and industry to conduct joint research projects and participated in multiple EU-funded research projects. He received several grants and awards for his research efforts, e.g., HiPEAC paper award, HiPEAC collaboration grant, Tetramax technology transfer grant, MSCA Seal of Excellence, I4MS Certificate of Excellence, OPRECOM Summer of Code, among others. His research interests are reconfigurable computing, low-power and fault-resilient hardware accelerators, and near data processing.''',
        })
        
    Speakers.objects.filter(name='Behzad Salami').update(
            picture='media/7th/speakers/Behzad-Salami.jpg',
            degree='PhD',
            place='Senior Researcher, ETH and BSC',
            polymorphic_ctype=ctype,
            bio='''Behzad Salami received the Ph.D. degree (Hons.) in Computer Architecture from the Universitat Politècnica de Catalunya  (UPC) in 2018, followed by a post-doc in the Computer Science department of Barcelona Supercomputing Centre (BSC). He is currently collaborating with the SAFARI Research Group as an affiliated researcher. He had short research visits at the University of Manchester (UK) and the Institute for Research in Fundamental Sciences (Iran). He has collaborated with academia and industry to conduct joint research projects and participated in multiple EU-funded research projects. He received several grants and awards for his research efforts, e.g., HiPEAC paper award, HiPEAC collaboration grant, Tetramax technology transfer grant, MSCA Seal of Excellence, I4MS Certificate of Excellence, OPRECOM Summer of Code, among others. His research interests are reconfigurable computing, low-power and fault-resilient hardware accelerators, and near data processing.''')

    Speakers.objects.get_or_create(
        name='Stefan Schmid',
        defaults={
            'picture': 'media/7th/speakers/Stefan-Schmid.jpg',
            'degree': 'PhD',
            'place': 'Professor, TU Berlin',
            'polymorphic_ctype': ctype,
            'bio': '''Stefan Schmid is a Professor at the Technical University of Berlin, Germany. MSc and PhD at ETH Zurich, Postdoc at TU Munich and University of Paderborn, Senior Research Scientist at  T-Labs in Berlin, Associate Professor at Aalborg University, Denmark, and Full Professor at the University of Vienna, Austria. Stefan Schmid received the IEEE Communications Society ITC Early Career Award 2016 and an ERC Consolidator Grant 2019.''',
        })
        
    Speakers.objects.filter(name='Stefan Schmid').update(
            picture='media/7th/speakers/Stefan-Schmid.jpg',
            degree='PhD',
            place='Professor, TU Berlin',
            polymorphic_ctype=ctype,
            bio='''Stefan Schmid is a Professor at the Technical University of Berlin, Germany. MSc and PhD at ETH Zurich, Postdoc at TU Munich and University of Paderborn, Senior Research Scientist at  T-Labs in Berlin, Associate Professor at Aalborg University, Denmark, and Full Professor at the University of Vienna, Austria. Stefan Schmid received the IEEE Communications Society ITC Early Career Award 2016 and an ERC Consolidator Grant 2019.''')

    Speakers.objects.get_or_create(
        name='Shahram Khazaei',
        defaults={
            'picture': 'media/7th/speakers/Shahram-Khazaei.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''I was a postdoctoral researcher at School of Computer Science and Communication, KTH Royal Institute of Technology, from 2011 to 2012 during which I worked with Douglas Wikström on electronic voting schemes and mix-nets. I did my Ph.D. at LACAL, EPFL, Switzerland under the supervision of Arjen Lenstra and Willi Meier and worked on cryptanalysis of symmetric primitives, mainly stream ciphers and hash functions.''',
        })
        
    Speakers.objects.filter(name='Shahram Khazaei').update(
            picture='media/7th/speakers/Shahram-Khazaei.jpg',
            degree='PhD',
            place='Assistant Professor, Sharif University of Technology',
            polymorphic_ctype=ctype,
            bio='''I was a postdoctoral researcher at School of Computer Science and Communication, KTH Royal Institute of Technology, from 2011 to 2012 during which I worked with Douglas Wikström on electronic voting schemes and mix-nets. I did my Ph.D. at LACAL, EPFL, Switzerland under the supervision of Arjen Lenstra and Willi Meier and worked on cryptanalysis of symmetric primitives, mainly stream ciphers and hash functions.''')

    Speakers.objects.get_or_create(
        name='Hadi Daneshmand',
        defaults={
            'picture': 'media/7th/speakers/Hadi-Daneshmand.jpg',
            'degree': 'PhD',
            'place': 'Postdoctoral Researcher, Princeton University',
            'polymorphic_ctype': ctype,
            'bio': '''Hadi is a postdoc at Princeton University. He previously worked at INRIA Paris as a postdoc researcher. Hadi completed his Ph.D. in computer science in June 2020 in the Machine Learning Department of ETH Zurich. The focus of his research is optimization for deep neural networks.''',
        })
        
    Speakers.objects.filter(name='Hadi Daneshmand').update(
            picture='media/7th/speakers/Hadi-Daneshmand.jpg',
            degree='PhD',
            place='Postdoctoral Researcher, Princeton University',
            polymorphic_ctype=ctype,
            bio='''Hadi is a postdoc at Princeton University. He previously worked at INRIA Paris as a postdoc researcher. Hadi completed his Ph.D. in computer science in June 2020 in the Machine Learning Department of ETH Zurich. The focus of his research is optimization for deep neural networks.''')

    Speakers.objects.get_or_create(
        name='Hassan Ashtiani',
        defaults={
            'picture': 'media/7th/speakers/Hassan-Ashtiani.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, McMaster University',
            'polymorphic_ctype': ctype,
            'bio': '''Hassan Ashtiani is an Assistant Professor in the Department of Computing and Software at McMaster University, and a faculty affiliate at Vector institute. He obtained his Ph.D. in Computer Science in 2018 from University of Waterloo where he was advised by Shai Ben-David. Before that, he received his master's degree in AI and Robotics and his bachelor's degree in Computer Engineering, both from University of Tehran. Broadly speaking, a major theme in his research is the design and analysis of sample-efficient learning algorithms. In recent years, he has focused on studying sample-efficient learning methods that are robust to (i) model misspecification, (ii) distribution shift, (iii) adversarial attacks, and/or (iv) privacy attacks.''',
        })
        
    Speakers.objects.filter(name='Hassan Ashtiani').update(
            picture='media/7th/speakers/Hassan-Ashtiani.jpg',
            degree='PhD',
            place='Assistant Professor, McMaster University',
            polymorphic_ctype=ctype,
            bio='''Hassan Ashtiani is an Assistant Professor in the Department of Computing and Software at McMaster University, and a faculty affiliate at Vector institute. He obtained his Ph.D. in Computer Science in 2018 from University of Waterloo where he was advised by Shai Ben-David. Before that, he received his master's degree in AI and Robotics and his bachelor's degree in Computer Engineering, both from University of Tehran. Broadly speaking, a major theme in his research is the design and analysis of sample-efficient learning algorithms. In recent years, he has focused on studying sample-efficient learning methods that are robust to (i) model misspecification, (ii) distribution shift, (iii) adversarial attacks, and/or (iv) privacy attacks.''')

    Speakers.objects.get_or_create(
        name='Pantea Zardoshti',
        defaults={
            'picture': 'media/7th/speakers/Pantea-Zardoshti.jpg',
            'degree': 'PhD',
            'place': 'Research Software Development Engineer 2 at Microsoft',
            'polymorphic_ctype': ctype,
            'bio': '''I am a Research Software Development Engineer in the Cloud Efficiency team within the Systems Research group. A central theme of my research is working on hardware/software co-design for improving the cost efficiency of Microsoft’s datacenters.

My PhD thesis focused on hardware/software co-design for emerging memory technologies, and compiler support for abstract instrumented memory interfaces, which allow programmers to exploit hardware and software memory features like persistent memory.''',
        })
        
    Speakers.objects.filter(name='Pantea Zardoshti').update(
            picture='media/7th/speakers/Pantea-Zardoshti.jpg',
            degree='PhD',
            place='Research Software Development Engineer 2 at Microsoft',
            polymorphic_ctype=ctype,
            bio='''I am a Research Software Development Engineer in the Cloud Efficiency team within the Systems Research group. A central theme of my research is working on hardware/software co-design for improving the cost efficiency of Microsoft’s datacenters.

My PhD thesis focused on hardware/software co-design for emerging memory technologies, and compiler support for abstract instrumented memory interfaces, which allow programmers to exploit hardware and software memory features like persistent memory.''')

    Speakers.objects.get_or_create(
        name='Kavé Salamatian',
        defaults={
            'picture': 'media/7th/speakers/Kavé-Salamatian.jpg',
            'degree': 'PhD',
            'place': 'Professor, Université de Savoie',
            'polymorphic_ctype': ctype,
            'bio': '''Kavé Salamatian is a full professor of computer science at University of Savoie. His main areas of researches have been Information theory applied to a large set of applications ranging from Internet measurement and modeling, Network architecture to cyber-security, and networking information theory. Kavé Salamatian has been educated as an electronics engineer in Isfahan University of technology from 1986. He has also graduated with a bachelor in maths (by correspondence) in the same year from Paris 6 university . He got an MBA in 1992 with a thesis titled « The application of Sun-Tse Strategy to marketing », a master in telecommunication in 1994 with a thesis titled « On the concept of capacity in neural nets » both from Isfahan University of Technology. He moved after to France and got  a master in theoretical computer science in 1996 with a thesis on joint source-channel coding applied to Internet transmission, continued with  a Phd in 1999 computer science at Paris South university, titled « Robust multimedia coding for video conferencing over Internet » and a habilitation to direct research in 2005, from Pierre and Marie Curie University. He has been holding Assistant and associate Professor at Pierre and Marie Curie University in Paris from 2000 to 2006, a visiting professor at EPFL and ETHZ till 2011.''',
        })
        
    Speakers.objects.filter(name='Kavé Salamatian').update(
            picture='media/7th/speakers/Kavé-Salamatian.jpg',
            degree='PhD',
            place='Professor, Université de Savoie',
            polymorphic_ctype=ctype,
            bio='''Kavé Salamatian is a full professor of computer science at University of Savoie. His main areas of researches have been Information theory applied to a large set of applications ranging from Internet measurement and modeling, Network architecture to cyber-security, and networking information theory. Kavé Salamatian has been educated as an electronics engineer in Isfahan University of technology from 1986. He has also graduated with a bachelor in maths (by correspondence) in the same year from Paris 6 university . He got an MBA in 1992 with a thesis titled « The application of Sun-Tse Strategy to marketing », a master in telecommunication in 1994 with a thesis titled « On the concept of capacity in neural nets » both from Isfahan University of Technology. He moved after to France and got  a master in theoretical computer science in 1996 with a thesis on joint source-channel coding applied to Internet transmission, continued with  a Phd in 1999 computer science at Paris South university, titled « Robust multimedia coding for video conferencing over Internet » and a habilitation to direct research in 2005, from Pierre and Marie Curie University. He has been holding Assistant and associate Professor at Pierre and Marie Curie University in Paris from 2000 to 2006, a visiting professor at EPFL and ETHZ till 2011.''')

    Speakers.objects.get_or_create(
        name='Peyman Mohajerin Esfahani',
        defaults={
            'picture': 'media/7th/speakers/Peyman-MohajerinEsfahani.jpg',
            'degree': 'PhD',
            'place': 'Associate Professor, Delft University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''Peyman Mohajerin Esfahani is an associate professor at the Delft Center for Systems and Control, and a co-director of the Delft-AI Energy Lab at the Delft University of Technology. Prior to joining TU Delft, he held several research appointments at EPFL, ETH Zurich, and MIT between 2014 and 2016. He received the BSc and MSc degrees from Sharif University of Technology, Iran, and the PhD degree from ETH Zurich. His research interests include theoretical and practical aspects of decision-making problems in uncertain and dynamic environments, with applications to control and security of large-scale and distributed systems. He was one of the three finalists for the Young Researcher Prize in Continuous Optimization awarded by the Mathematical Optimization Society in 2016, and was a recipient of the 2016 George S. Axelby Outstanding Paper Award from the IEEE Control Systems Society. He also received the ERC Starting Grant and the INFORMS Frederick W. Lanchester Prize in 2020.''',
        })
        
    Speakers.objects.filter(name='Peyman Mohajerin Esfahani').update(
            picture='media/7th/speakers/Peyman-MohajerinEsfahani.jpg',
            degree='PhD',
            place='Associate Professor, Delft University of Technology',
            polymorphic_ctype=ctype,
            bio='''Peyman Mohajerin Esfahani is an associate professor at the Delft Center for Systems and Control, and a co-director of the Delft-AI Energy Lab at the Delft University of Technology. Prior to joining TU Delft, he held several research appointments at EPFL, ETH Zurich, and MIT between 2014 and 2016. He received the BSc and MSc degrees from Sharif University of Technology, Iran, and the PhD degree from ETH Zurich. His research interests include theoretical and practical aspects of decision-making problems in uncertain and dynamic environments, with applications to control and security of large-scale and distributed systems. He was one of the three finalists for the Young Researcher Prize in Continuous Optimization awarded by the Mathematical Optimization Society in 2016, and was a recipient of the 2016 George S. Axelby Outstanding Paper Award from the IEEE Control Systems Society. He also received the ERC Starting Grant and the INFORMS Frederick W. Lanchester Prize in 2020.''')

    Speakers.objects.get_or_create(
        name='Farzan Farnia',
        defaults={
            'picture': 'media/7th/speakers/Farzan-Farnia.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, The Chinese University of Hong Kong',
            'polymorphic_ctype': ctype,
            'bio': '''Farzan Farnia is an Assistant Professor of Computer Science and Engineering at The Chinese University of Hong Kong. Prior to joining CUHK, he was a postdoctoral research associate at the Laboratory for Information and Decision Systems, Massachusetts Institute of Technology, from 2019-2021. He received his master’s and PhD degrees in electrical engineering from Stanford University and his bachelor’s degrees in electrical engineering and mathematics from Sharif University of Technology. At Stanford, he was a graduate research assistant at the Information Systems Laboratory advised by Professor David Tse. Farzan's research interests span statistical learning theory, information theory, and convex optimization. He has been the recipient of the Stanford Graduate Fellowship (Sequoia Capital Fellowship) between 2013-2016 and the Numerical Technology Founders Prize as the second top performer of Stanford’s electrical engineering PhD qualifying exams in 2014.''',
        })
        
    Speakers.objects.filter(name='Farzan Farnia').update(
            picture='media/7th/speakers/Farzan-Farnia.jpg',
            degree='PhD',
            place='Assistant Professor, The Chinese University of Hong Kong',
            polymorphic_ctype=ctype,
            bio='''Farzan Farnia is an Assistant Professor of Computer Science and Engineering at The Chinese University of Hong Kong. Prior to joining CUHK, he was a postdoctoral research associate at the Laboratory for Information and Decision Systems, Massachusetts Institute of Technology, from 2019-2021. He received his master’s and PhD degrees in electrical engineering from Stanford University and his bachelor’s degrees in electrical engineering and mathematics from Sharif University of Technology. At Stanford, he was a graduate research assistant at the Information Systems Laboratory advised by Professor David Tse. Farzan's research interests span statistical learning theory, information theory, and convex optimization. He has been the recipient of the Stanford Graduate Fellowship (Sequoia Capital Fellowship) between 2013-2016 and the Numerical Technology Founders Prize as the second top performer of Stanford’s electrical engineering PhD qualifying exams in 2014.''')

    Speakers.objects.get_or_create(
        name='Maryam Kamgarpour',
        defaults={
            'picture': 'media/7th/speakers/Maryam-Kamgarpour.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, EPFL',
            'polymorphic_ctype': ctype,
            'bio': '''Maryam Kamgarpour holds a Doctor of Philosophy in Engineering from the University of California, Berkeley and a Bachelor of Applied Science from University of Waterloo, Canada. Her research is on safe decision-making and control under uncertainty, game theory and mechanism design, mixed integer and stochastic optimization and control. Her theoretical research is motivated by control challenges arising in intelligent transportation networks, robotics, power grid systems and healthcare. She is the recipient of NASA High Potential Individual Award, NASA Excellence in Publication Award, and the European Union (ERC) Starting Grant.''',
        })
        
    Speakers.objects.filter(name='Maryam Kamgarpour').update(
            picture='media/7th/speakers/Maryam-Kamgarpour.jpg',
            degree='PhD',
            place='Assistant Professor, EPFL',
            polymorphic_ctype=ctype,
            bio='''Maryam Kamgarpour holds a Doctor of Philosophy in Engineering from the University of California, Berkeley and a Bachelor of Applied Science from University of Waterloo, Canada. Her research is on safe decision-making and control under uncertainty, game theory and mechanism design, mixed integer and stochastic optimization and control. Her theoretical research is motivated by control challenges arising in intelligent transportation networks, robotics, power grid systems and healthcare. She is the recipient of NASA High Potential Individual Award, NASA Excellence in Publication Award, and the European Union (ERC) Starting Grant.''')

    Speakers.objects.get_or_create(
        name='Azam Soleimanian',
        defaults={
            'picture': 'media/7th/speakers/Azam-Soleimanian.jpg',
            'degree': 'PhD',
            'place': 'Researcher, EPFL',
            'polymorphic_ctype': ctype,
            'bio': '''Azam Soleimanian is currently an applied researcher in the ConsenSys company working on the scalability of Ethereum blockchain.  She has received her PhD in 2018 under the supervision of Dr. Shahram Khazaei.  She joined the university of Catania for a one-year academic-visit to collaborate with Dr. Dario Catalano. After that,  she worked as a postadoc researcher at Cascad team of ENS and Grace team of Ecole Polytechnique (Paris, France) where she collaborated with Dr. Michel Abdalla and Dr. David Pointcheval.''',
        })
        
    Speakers.objects.filter(name='Azam Soleimanian').update(
            picture='media/7th/speakers/Azam-Soleimanian.jpg',
            degree='PhD',
            place='Researcher, EPFL',
            polymorphic_ctype=ctype,
            bio='''Azam Soleimanian is currently an applied researcher in the ConsenSys company working on the scalability of Ethereum blockchain.  She has received her PhD in 2018 under the supervision of Dr. Shahram Khazaei.  She joined the university of Catania for a one-year academic-visit to collaborate with Dr. Dario Catalano. After that,  she worked as a postadoc researcher at Cascad team of ENS and Grace team of Ecole Polytechnique (Paris, France) where she collaborated with Dr. Michel Abdalla and Dr. David Pointcheval.''')

    Speakers.objects.get_or_create(
        name='Mohammad Sadrosadati',
        defaults={
            'picture': 'media/7th/speakers/Mohammad-Sadrosadati.jpg',
            'degree': 'PhD',
            'place': 'Senior Researcher, ETH',
            'polymorphic_ctype': ctype,
            'bio': '''Mohammad Sadrosadati received Ph.D. degree in Computer Engineering from Sharif University of Technology, Tehran, Iran, in 2019 under the supervision of Prof. H. Sarbazi-Azad. He spent one year from April 2017 to April 2018 as an academic guest at ETH Zurich hosted by Prof. O. Mutlu during his Ph.D. program. He is currently a senior researcher in the SAFARI research group at ETH Zurich. His research interests are in the areas of heterogeneous computing, processing-in-memory, memory systems, and interconnection networks. Due to his achievements and impact on improving the energy efficiency of GPUs, he won Khwarizmi Youth Award, one of the most prestigious awards, as the first laureate in 2020, to honor and embolden him to keep taking even bigger steps in his research career.''',
        })
        
    Speakers.objects.filter(name='Mohammad Sadrosadati').update(
            picture='media/7th/speakers/Mohammad-Sadrosadati.jpg',
            degree='PhD',
            place='Senior Researcher, ETH',
            polymorphic_ctype=ctype,
            bio='''Mohammad Sadrosadati received Ph.D. degree in Computer Engineering from Sharif University of Technology, Tehran, Iran, in 2019 under the supervision of Prof. H. Sarbazi-Azad. He spent one year from April 2017 to April 2018 as an academic guest at ETH Zurich hosted by Prof. O. Mutlu during his Ph.D. program. He is currently a senior researcher in the SAFARI research group at ETH Zurich. His research interests are in the areas of heterogeneous computing, processing-in-memory, memory systems, and interconnection networks. Due to his achievements and impact on improving the energy efficiency of GPUs, he won Khwarizmi Youth Award, one of the most prestigious awards, as the first laureate in 2020, to honor and embolden him to keep taking even bigger steps in his research career.''')

    Speakers.objects.get_or_create(
        name='Mohammad Hossein Rohban',
        defaults={
            'picture': 'media/7th/speakers/Mohammad-Hossein-Rohban.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''Mohammad Hossein Rohban is an assistant professor in Computer Engineering Department of Sharif University of Technology. His research areas include adversarial robustness, anomaly detection, and medical imaging. Previously, he was a postdoc at Broad Institute of MIT and Harvard, where his research was focused around applications of ML and data analysis on Microscopy data that makes gene and compound function characterization possible.''',
        })
        
    Speakers.objects.filter(name='Mohammad Hossein Rohban').update(
            picture='media/7th/speakers/Mohammad-Hossein-Rohban.jpg',
            degree='PhD',
            place='Assistant Professor, Sharif University of Technology',
            polymorphic_ctype=ctype,
            bio='''Mohammad Hossein Rohban is an assistant professor in Computer Engineering Department of Sharif University of Technology. His research areas include adversarial robustness, anomaly detection, and medical imaging. Previously, he was a postdoc at Broad Institute of MIT and Harvard, where his research was focused around applications of ML and data analysis on Microscopy data that makes gene and compound function characterization possible.''')


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Hamed Haddadi', 'Pooya Hatami', 'Amir Moradi', 'Mohammad Hajiabadi',
             'Soheil Abbasloo', 'Amir Zamir', 'Mahdi Cheraghchi', 'Masoumeh Ebrahimi', 'Amir Shaikhha',
             'Behzad Salami', 'Stefan Schmid', 'Shahram Khazaei', 'Hadi Daneshmand', 'Hassan Ashtiani',
             'Pantea Zardoshti', 'Kavé Salamatian', 'Peyman Mohajerin Esfahani', 'Farzan Farnia',
             'Maryam Kamgarpour', 'Azam Soleimanian', 'Mohammad Sadrosadati', 'Mohammad Hossein Rohban', ]
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_fill_7th_speakers_data'),
        ('WSS', '0019_add_7th_WSS'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
