# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Mohammad Shahrad',
        defaults={
            'picture': 'media/7th/speakers/Mohammad-Shahrad.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, The University of British Columbia',
            'polymorphic_ctype': ctype,
            'bio': '''Mohammad Shahrad is an Assistant Professor of Electrical and Computer Engineering at The University of British Columbia (UBC). He is broadly interested in improving the efficiency of cloud computing systems and has worked across the stack toward this goal. This includes building novel scheduling schemes for VMs and serverless workloads, modeling user-provider interactions to propose new pricing models, and building a new processor for efficient off-chip scalability of cloud workloads. Before joining UBC, Mohammad was a lecturer at the Princeton University Computer Science Department. He holds a Ph.D. in Electrical Engineering from Princeton University and spent a year at Microsoft Research working on cloud efficiency projects. Mohammad is a Sharif EE alum.''',
        })
        
    Speakers.objects.filter(name='Mohammad Shahrad').update(
            picture='media/7th/speakers/Mohammad-Shahrad.jpg',
            degree='PhD',
            place='Assistant Professor, The University of British Columbia',
            polymorphic_ctype=ctype,
            bio='''Mohammad Shahrad is an Assistant Professor of Electrical and Computer Engineering at The University of British Columbia (UBC). He is broadly interested in improving the efficiency of cloud computing systems and has worked across the stack toward this goal. This includes building novel scheduling schemes for VMs and serverless workloads, modeling user-provider interactions to propose new pricing models, and building a new processor for efficient off-chip scalability of cloud workloads. Before joining UBC, Mohammad was a lecturer at the Princeton University Computer Science Department. He holds a Ph.D. in Electrical Engineering from Princeton University and spent a year at Microsoft Research working on cloud efficiency projects. Mohammad is a Sharif EE alum.''')


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Mohammad Shahrad', ]
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_update_7th_speakers_data'),
        ('WSS', '0021_discountcode'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
