# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Iman Hajirasouliha',
        defaults={
            'picture': 'media/7th/speakers/Iman-Hajirasouliha.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, Weill Cornell Medicine of Cornell University',
            'polymorphic_ctype': ctype,
            'bio': '''Iman Hajirasouliha is Assistant Professor of Computational Genomics at the Institute for Computational Biomedicine at Weill Cornell Medicine of Cornell University and a member of the Englander Institute for Precision Medicine and the Meyer Cancer Center, New York, USA. He completed a Postdoctoral Scholarship at the Computer Science Department, Stanford University, and a Simons Research Fellowship at the University of California, Berkeley. His research focuses on computational genomics, computational digital pathology, large-scale sequence analysis, and characterizing somatic variations and intra-tumor heterogeneity in cancer. Iman received his B.Sc. in Computer Engineering from Sharif University and his M.Sc. in Computing Science from Simon Fraser University (SFU). He obtained his Ph.D. with Exceptional Recognition from SFU and also held a postdoctoral appointment at Brown University. During his Ph.D., Iman was also a student collaborator at Canada's Michael Smith Genome Sciences Centre and a visiting scholar at the Department of Genome Sciences, University of Washington.''',
        })
        
    Speakers.objects.filter(name='Iman Hajirasouliha').update(
            picture='media/7th/speakers/Iman-Hajirasouliha.jpg',
            degree='PhD',
            place='Assistant Professor, Weill Cornell Medicine of Cornell University',
            polymorphic_ctype=ctype,
            bio='''Iman Hajirasouliha is Assistant Professor of Computational Genomics at the Institute for Computational Biomedicine at Weill Cornell Medicine of Cornell University and a member of the Englander Institute for Precision Medicine and the Meyer Cancer Center, New York, USA. He completed a Postdoctoral Scholarship at the Computer Science Department, Stanford University, and a Simons Research Fellowship at the University of California, Berkeley. His research focuses on computational genomics, computational digital pathology, large-scale sequence analysis, and characterizing somatic variations and intra-tumor heterogeneity in cancer. Iman received his B.Sc. in Computer Engineering from Sharif University and his M.Sc. in Computing Science from Simon Fraser University (SFU). He obtained his Ph.D. with Exceptional Recognition from SFU and also held a postdoctoral appointment at Brown University. During his Ph.D., Iman was also a student collaborator at Canada's Michael Smith Genome Sciences Centre and a visiting scholar at the Department of Genome Sciences, University of Washington.''')


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Iman Hajirasouliha', ]
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_add_new_7th_speaker_data'),
        ('WSS', '0021_discountcode'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
