# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Hamid R. Rabiee',
        defaults={
            'picture': 'media/7th/speakers/Hamid-R-Rabiee.jpg',
            'degree': 'PhD',
            'place': 'Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })
    Speakers.objects.filter(name='Hamid R. Rabiee').update(
            picture='media/7th/speakers/Hamid-R-Rabiee.jpg',
            polymorphic_ctype=ctype,)

    Speakers.objects.get_or_create(
        name='Abbas Heydarnoori',
        defaults={
            'picture': 'media/7th/speakers/Abbas-Heydarnoori.jpg',
            'degree': 'PhD',
            'place': 'Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })
    Speakers.objects.filter(name='Abbas Heydarnoori').update(
            picture='media/7th/speakers/Abbas-Heydarnoori.jpg',
            polymorphic_ctype=ctype,)

    Speakers.objects.get_or_create(
        name='Alireza Ejlali',
        defaults={
            'picture': 'media/7th/speakers/Alireza-Ejlali.jpg',
            'degree': 'PhD',
            'place': 'Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })
    Speakers.objects.filter(name='Alireza Ejlali').update(
            picture='media/7th/speakers/Alireza-Ejlali.jpg',
            polymorphic_ctype=ctype,)


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    Labtalk = apps.get_model('event', 'LabTalk')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Hamid R. Rabiee', ]
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    Labtalk.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_add_newer_7th_speaker_data'),
        ('WSS', '0021_discountcode'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
