# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Amir Moradi',
        defaults={
            'picture': 'media/7th/speakers/Amir-Moradi.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Hamed Hassani',
        defaults={
            'picture': 'media/7th/speakers/Hamed-Hassani.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Abolfazl Motahari',
        defaults={
            'picture': 'media/7th/speakers/Abolfazl-Motahari.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Soheil Abbaslooa',
        defaults={
            'picture': 'media/7th/speakers/Soheil-Abbaslooa.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Kavé Salamatian',
        defaults={
            'picture': 'media/7th/speakers/Kavé-Salamatian.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Amir Zamir',
        defaults={
            'picture': 'media/7th/speakers/Amir-Zamir.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Hamed Haddadi',
        defaults={
            'picture': 'media/7th/speakers/Hamed-Haddadi.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Hadi Daneshmand',
        defaults={
            'picture': 'media/7th/speakers/Hadi-Daneshmand.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Hessam Bagherinezhad',
        defaults={
            'picture': 'media/7th/speakers/Hessam-Bagherinezhad.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })

    Speakers.objects.get_or_create(
        name='Mahdi Cheraghchi',
        defaults={
            'picture': 'media/7th/speakers/Mahdi-Cheraghchi.jpg',
            'degree': '',
            'place': '',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_add_labtalk_7th_speaker_data'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
