# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Hamid R. Rabiee',
        defaults={
            'picture': 'media/7th/speakers/Hamid-R-Rabiee.jpg',
            'degree': 'PhD',
            'place': 'Professor, Department of Computer Engineering, Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''Hamid R. Rabiee received his BS and MS degrees (with Great Distinction) in Electrical Engineering from CSULB, Long Beach, CA (1987, 1989), his EEE degree in Electrical and Computer Engineering from USC, Los Angeles, CA (1993), and his Ph.D. in Electrical and Computer Engineering from Purdue University, West Lafayette, IN, in 1996. From 1993 to 1996 he was a Member of Technical Staff at AT&T Bell Laboratories. From 1996 to 1999 he worked as a Senior Software Engineer at Intel Corporation. He was also with PSU, OGI and OSU universities as an adjunct professor of Electrical and Computer Engineering from 1996-2000. Since September 2000, he has joined Sharif University of Technology, Tehran, Iran. He was also a visiting professor at the Imperial College of London for the 2017-2018 academic year. He is the founder of Sharif University Advanced Information and Communication Technology Research Institute (AICT), ICT Innovation Center, Advanced Technologies Incubator (SATI), Data Science & Machine Learning Laboratory (DML), Mobile Value Added Services Laboratory (M-VASL), Bioinformatics and Computational Biology Laboratory (BCB) and Cognitive Neuroengineering Research Center (CNRC). He has also been the founder of many successful High-Tech start-up companies in the field of ICT as an entrepreneur. He is currently a Professor of Computer Engineering at Sharif University of Technology, and Director of AICT, DML, and M-VASL. He has been the initiator and director of many national and international level projects in the context of Iran National ICT Development Plan and UNDP International Open Source Network. He is also a consultant and member of AI in Health Expert Group at WHO. He has received numerous awards and honors for his Industrial, scientific and academic contributions, and holds three patents. He is also a Senior Member of IEEE. His research interests include statistical machine learning, Bayesian statistics, data analytics and complex networks with applications in social networks, multimedia systems, cloud and IoT privacy, bioinformatics, and brain networks.''',
        })
    Speakers.objects.filter(name='Hamid R. Rabiee').update(
            picture='media/7th/speakers/Hamid-R-Rabiee.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Professor, Department of Computer Engineering, Sharif University of Technology',
            bio='''Hamid R. Rabiee received his BS and MS degrees (with Great Distinction) in Electrical Engineering from CSULB, Long Beach, CA (1987, 1989), his EEE degree in Electrical and Computer Engineering from USC, Los Angeles, CA (1993), and his Ph.D. in Electrical and Computer Engineering from Purdue University, West Lafayette, IN, in 1996. From 1993 to 1996 he was a Member of Technical Staff at AT&T Bell Laboratories. From 1996 to 1999 he worked as a Senior Software Engineer at Intel Corporation. He was also with PSU, OGI and OSU universities as an adjunct professor of Electrical and Computer Engineering from 1996-2000. Since September 2000, he has joined Sharif University of Technology, Tehran, Iran. He was also a visiting professor at the Imperial College of London for the 2017-2018 academic year. He is the founder of Sharif University Advanced Information and Communication Technology Research Institute (AICT), ICT Innovation Center, Advanced Technologies Incubator (SATI), Data Science & Machine Learning Laboratory (DML), Mobile Value Added Services Laboratory (M-VASL), Bioinformatics and Computational Biology Laboratory (BCB) and Cognitive Neuroengineering Research Center (CNRC). He has also been the founder of many successful High-Tech start-up companies in the field of ICT as an entrepreneur. He is currently a Professor of Computer Engineering at Sharif University of Technology, and Director of AICT, DML, and M-VASL. He has been the initiator and director of many national and international level projects in the context of Iran National ICT Development Plan and UNDP International Open Source Network. He is also a consultant and member of AI in Health Expert Group at WHO. He has received numerous awards and honors for his Industrial, scientific and academic contributions, and holds three patents. He is also a Senior Member of IEEE. His research interests include statistical machine learning, Bayesian statistics, data analytics and complex networks with applications in social networks, multimedia systems, cloud and IoT privacy, bioinformatics, and brain networks.''')

    Speakers.objects.get_or_create(
        name='Abbas Heydarnoori',
        defaults={
            'picture': 'media/7th/speakers/Abbas-Heydarnoori.jpg',
            'degree': 'PhD',
            'place': 'Assistant Professor, Department of Computer Engineering, Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''Abbas Heydarnoori has been a faculty member in the Department of Computer Engineering at the Sharif University of Technology since 2012. Before joining the Sharif University of Technology, he worked as a Software Engineer at Xtreme Labs Inc. (acquired by Pivotal), Toronto, Canada in 2011. Before that, in 2010, he was a post-doctoral fellow in the Faculty of Informatics at the University of Lugano, Switzerland working with Prof. Walter Binder. He finished his PhD studies in 2009 under the supervision of Prof. Krzysztof Czarnecki in the School of Computer Science at the University of Waterloo, Canada. The details of his PhD research can be obtained from here. He also received his MSc and BSc degrees from the Department of Computer Engineering at the Sharif University of Technology, Iran in 2001 and 1999 respectively.''',
        })
    Speakers.objects.filter(name='Abbas Heydarnoori').update(
            picture='media/7th/speakers/Abbas-Heydarnoori.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Assistant Professor, Department of Computer Engineering, Sharif University of Technology',
            bio='''Abbas Heydarnoori has been a faculty member in the Department of Computer Engineering at the Sharif University of Technology since 2012. Before joining the Sharif University of Technology, he worked as a Software Engineer at Xtreme Labs Inc. (acquired by Pivotal), Toronto, Canada in 2011. Before that, in 2010, he was a post-doctoral fellow in the Faculty of Informatics at the University of Lugano, Switzerland working with Prof. Walter Binder. He finished his PhD studies in 2009 under the supervision of Prof. Krzysztof Czarnecki in the School of Computer Science at the University of Waterloo, Canada. The details of his PhD research can be obtained from here. He also received his MSc and BSc degrees from the Department of Computer Engineering at the Sharif University of Technology, Iran in 2001 and 1999 respectively.''')

    Speakers.objects.get_or_create(
        name='Alireza Ejlali',
        defaults={
            'picture': 'media/7th/speakers/Alireza-Ejlali.jpg',
            'degree': 'PhD',
            'place': 'Associate Professor, Department of Computer Engineering, Sharif University of Technology',
            'polymorphic_ctype': ctype,
            'bio': '''Alireza Ejlali is an Associate Professor of Computer Science and Engineering at Sharif University of Technology, Tehran, Iran. He received a Ph.D. degree in computer engineering from Sharif University of Technology in 2006. From 2005 to 2006, he was a visiting researcher in the Electronic Systems Design Group, University of Southampton, UK. In 2006 he joined Sharif University of Technology as a faculty member in the department of computer science and engineering and from 2011 to 2015, he was the director of Computer Architecture Group in this department. He is now the director of Embedded Systems Research Laboratory (ESR-LAB) and the head of the department of computer science and engineering, Sharif University of Technology. His research interests include low power design, fault tolerance, real-time embedded systems, and Internet of Things (IoT).''',
        })
    Speakers.objects.filter(name='Alireza Ejlali').update(
            picture='media/7th/speakers/Alireza-Ejlali.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Assistant Professor, Department of Computer Engineering, Sharif University of Technology',
            bio='''Alireza Ejlali is an Associate Professor of Computer Science and Engineering at Sharif University of Technology, Tehran, Iran. He received a Ph.D. degree in computer engineering from Sharif University of Technology in 2006. From 2005 to 2006, he was a visiting researcher in the Electronic Systems Design Group, University of Southampton, UK. In 2006 he joined Sharif University of Technology as a faculty member in the department of computer science and engineering and from 2011 to 2015, he was the director of Computer Architecture Group in this department. He is now the director of Embedded Systems Research Laboratory (ESR-LAB) and the head of the department of computer science and engineering, Sharif University of Technology. His research interests include low power design, fault tolerance, real-time embedded systems, and Internet of Things (IoT).''')


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    Seminar = apps.get_model('event', 'Seminar')
    Labtalk = apps.get_model('event', 'LabTalk')
    PosterSession = apps.get_model('events', 'PosterSession')
    Workshop = apps.get_model('events', 'Workshop')
    names = ['Hamid R. Rabiee', 'Abbas Heydarnoori', 'Alireza Ejlali']
    speakers = Speakers.objects.filter(name__in=names)
    Seminar.objects.filter(speaker__in=speakers).delete()
    Labtalk.objects.filter(speaker__in=speakers).delete()
    PosterSession.objects.filter(speaker__in=speakers).delete()
    Workshop.objects.filter(speaker__in=speakers).delete()
    speakers.delete()

    Speakers.objects.filter(name='Hamid R. Rabiee').update(
            picture='media/7th/speakers/Hamid-R-Rabiee.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Sharif University of Technology',
            bio='''''')

    Speakers.objects.filter(name='Abbas Heydarnoori').update(
            picture='media/7th/speakers/Abbas-Heydarnoori.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Sharif University of Technology',
            bio='''''')

    Speakers.objects.filter(name='Alireza Ejlali').update(
            picture='media/7th/speakers/Alireza-Ejlali.jpg',
            polymorphic_ctype=ctype,
            degree='PhD',
            place='Sharif University of Technology',
            bio='''''')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_update_speakers'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
