# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')

    Speakers.objects.filter(name='Abolfazl Motahari').update(
        degree='Ph.D.', place='Assistant Professor, Sharif University of Technology')

    Speakers.objects.filter(name='Hessam Bagherinezhad').update(
        degree='Ph.D.', place='Assistant Professor, Senior Machine Learning Engineer, Apple')


def rollback(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')

    Speakers.objects.filter(name='Abolfazl Motahari').update(
        degree='', place='')

    Speakers.objects.filter(name='Hessam Bagherinezhad').update(
        degree='', place='')


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_add_event_general_speaker'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
