# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Speakers = apps.get_model('people', 'Speaker')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Speakers)

    Speakers.objects.get_or_create(
        name='Arash Pourdamghani',
        defaults={
            'picture': 'media/7th/speakers/Amir-Moradi.jpg',
            'degree': 'Ph.D. Student',
            'place': 'Researcher, Intelligent Networks (INET), TU Berlin',
            'polymorphic_ctype': ctype,
            'bio': '''''',
        })


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0042_add_roundtable_speaker_titles'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
