# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    WSS = apps.get_model('WSS', 'WSS')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(Staff)

    teams_staff = {
        'Secretary': ['Farzam Zohdinasab'],
        'Deputy Secretary': ['Ali Sharifi'],
        'Human Resources': ['Mahdi Alizadeh', 'Iman Mohammadi', 'Negar Babashah', 'Ali Rahmizad', 'Nasser Kazemi', 'Pardis Zahraei', 'Bahar Dibaienia'],
        'Branding': ['Mohammad Abolnezhadian', 'Hossein Yousefi', 'Sara Azarnoosh', 'Siavash Rahimi Shaterloo', 'Hamed Alimohammadzadeh', 'Soheil Nazari'],
        'Scientific': ['Mahdi Akhi', 'Kimia Noorbakhsh', 'Amirmahdi Namjoo', 'Mahdi Farvardin', 'Arshia Moghimi'],
        'Social Network': ['Mehrad Milanloo', 'Reyhaneh Zohrabi', 'Hamraz Arafati', 'Kian Bahadori', 'Sabiheh Tajdari', 'Roya Daneshi', 'Mohammad Ali Mohammadkhani', 'Ali Javanmard'],
        'Technical': ['Soroush Jahanzad', 'Mohammad Hossein Dolatabadi', 'Soroush Sherafat', 'Yasmin Kadkhodaei', 'Ali asghar Ghanati', 'Mohammad Mahdi Barghi', 'Mohammad Sadegh Majidi'],
        'Media': ['Mahdiyeh Ebrahimpoor', 'Pooya Setayesh', 'Saee Sa\'adat', 'Behzad Nabavi', 'Pooya Yousefi', 'Seyyed Hessamoddin Soleymani', 'Sara Zahedi Movahhed', 'Mohammad Mosayyebi'],
        'Sponsorship': ['Sina Elahimanesh', 'Majid Taherkhani', 'Mohammad Hossein Soleymani', 'Bardia Mohammadi'],
        'Executive': ['Donya Navvabi', 'Mobina Salimipanah', 'Aryan Zamani', 'Hasti Karimi', 'Fatemeh Alimoradi', 'Kiana Mousazadeh', 'Amirhossein Abedi', 'Mohammad Moshtaghi', 'Sheima Ramadani', 'Seyyed Mohammad Pouriya Momtaz Esfahani'],
    }

    wss = WSS.objects.get(year=2021)

    for team_name in teams_staff:
        team = HoldingTeam.objects.create(wss=wss, name=team_name)
        for staff_name in teams_staff[team_name]:
            staff = Staff.objects.create(
                name=staff_name,
                picture='media/7th/staff/' +
                '-'.join(staff_name.split()) + '.jpg',
                polymorphic_ctype=ctype,
            )
            team.staff.add(staff)
        team.save()
        # team.staff.set(Staff.objects.filter(
        #     name__in=teams_staff[team_name]).order_by('id'))


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_update_roundtable_speaker_place'),
    ]

    operations = [
        migrations.RunPython(forwards, rollback)
    ]
