# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Staff = apps.get_model('people', 'Staff')
    WSS = apps.get_model('WSS', 'WSS')
    HoldingTeam = apps.get_model('people', 'HoldingTeam')
    wss = WSS.objects.get(year=2021)

    HoldingTeam.objects.filter(wss=wss, name='Deputy Secretary').delete()
    Staff.objects.filter(name='Ali Sharifi').delete()

    s = Staff.objects.get(name='Mohammad Abolnezhadian')
    team = HoldingTeam.objects.filter(wss=wss, name='Branding').staff.remove(s)
    team.save()
    team = HoldingTeam.objects.filter(wss=wss, name='Sponsorship').staff.add(s)
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_add_7th_scientific_advisors_to_staff'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
