---
all:
  vars:
    shecan_dns_1: 185.51.200.2
    shecan_dns_2: 178.22.122.100
    src_root_dir: '../'
    dest_root_dir: '/home/{{ ansible_user }}/wss/'
    docker_hub_username: 'sharifwss'
    docker_hub_password: '{{ lookup("env", "DOCKER_PASSWORD") }}'
  children:
    production:
      hosts:
        prod1:
          sudo_pass: '{{ lookup("env", "SERVER_PROD_PASS") }}'
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_sudo_pass: '{{ sudo_pass }}'
          ansible_become_pass: '{{ sudo_pass }}'
