---
- hosts: all
  become: yes
  tasks:
    - name: 'Check mandatory variables are defined'
      assert:
        that:
          - shecan_dns_1 is defined
          - shecan_dns_2 is defined

    - name: Install python-apt using apt
      apt:
        name: python-apt
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: no
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-pip
        - virtualenv
        - python-setuptools
        - docker-compose
        - python-dev

    - name: Set Shecan
      shell: "echo '### Shecan DNS ###\nnameserver {{ shecan_dns_1 | mandatory }}\nnameserver {{ shecan_dns_2 | mandatory }}' > /etc/resolv.conf"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install ansible docker_compose module dependencies
      pip:
        name:
          - docker==4.2.0
          - docker-compose==1.25.5
          - PyYAML==5.3.1
        extra_args: --user
        executable: /usr/bin/pip

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups:
          - docker
          - sudo

    - name: Create docker config parent directory
      file:
        path: /etc/systemd/system/docker.service.d/
        state: directory

    - name: Add docker.ir proxy config
      copy:
        content: |
          [Service]
          Environment="HTTP_PROXY=http://Proxy.Docker.ir:5555"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        

    # Ansible 'service' module didn't work after 1 week try!
    - name: Restart docker manually!
      shell: "systemctl daemon-reload && service docker restart"

    - name: Post check
      command: "{{ item }}"
      loop:
        - docker info
        - docker-compose --version
