# Generated by Django 4.2.8 on 2024-02-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participant", "0002_participation_spotplayer_license_and_more"),
        ("skyroom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skyroomevent",
            name="plan",
        ),
        migrations.AddField(
            model_name="skyroomevent",
            name="plans",
            field=models.ManyToManyField(to="participant.participationplan"),
        ),
    ]
