# Generated by Django 4.2.8 on 2024-02-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotPlayerCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=100)),
                ("course_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SpotPlayerLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_id", models.CharField(max_length=100)),
                ("license_key", models.CharField(max_length=200)),
                ("license_url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SpotPlayerCourseLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotplayer.spotplayercourse",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotplayer.spotplayerlicense",
                    ),
                ),
            ],
        ),
    ]
