// account:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const SEND_PAYMENT_REQUEST = 'SEND_PAYMENT_REQUEST';
export const SEND_PAYMENT_SUCCESS = 'SEND_PAYMENT_SUCCESS';
export const SEND_PAYMENT_FAILURE = 'SEND_PAYMENT_FAILURE';

export const VERIFY_PAYMENT_REQUEST = 'VERIFY_PAYMENT_REQUEST';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAILURE = 'VERIFY_PAYMENT_FAILURE';

export const CHECK_USER_REGISTRATION_STATUS_REQUEST = 'CHECK_USER_REGISTRATION_STATUS_REQUEST';
export const CHECK_USER_REGISTRATION_STATUS_SUCCESS = 'CHECK_USER_REGISTRATION_STATUS_SUCCESS';
export const CHECK_USER_REGISTRATION_STATUS_FAILURE = 'CHECK_USER_REGISTRATION_STATUS_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const REQUEST_PASSWORD_RESET_REQUEST = 'REQUEST_PASSWORD_RESET_REQUEST';
export const REQUEST_PASSWORD_RESET_SUCCESS = 'REQUEST_PASSWORD_RESET_SUCCESS';
export const REQUEST_PASSWORD_RESET_FAILURE = 'REQUEST_PASSWORD_RESET_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// participant

export const GET_REGISTERED_WORKSHOPS_REQUEST = 'GET_REGISTERED_WORKSHOPS_REQUEST';
export const GET_REGISTERED_WORKSHOPS_SUCCESS = 'GET_REGISTERED_WORKSHOPS_SUCCESS';
export const GET_REGISTERED_WORKSHOPS_FAILURE = 'GET_REGISTERED_WORKSHOPS_FAILURE';

export const REGISTER_WORKSHOP_REQUEST = 'REGISTER_WORKSHOP_REQUEST';
export const REGISTER_WORKSHOP_SUCCESS = 'REGISTER_WORKSHOP_SUCCESS';
export const REGISTER_WORKSHOP_FAILURE = 'REGISTER_WORKSHOP_FAILURE';

export const CANCEL_WORKSHOP_REGISTRATION_REQUEST = 'CANCEL_WORKSHOP_REGISTRATION_REQUEST';
export const CANCEL_WORKSHOP_REGISTRATION_SUCCESS = 'CANCEL_WORKSHOP_REGISTRATION_SUCCESS';
export const CANCEL_WORKSHOP_REGISTRATION_FAILURE = 'CANCEL_WORKSHOP_REGISTRATION_FAILURE';

// WSS:

export const PRIMITIVE_FIELDS_REQUEST = 'PRIMITIVE_FIELDS_REQUEST';
export const PRIMITIVE_FIELDS_SUCCESS = 'PRIMITIVE_FIELDS_SUCCESS';
export const PRIMITIVE_FIELDS_FAILURE = 'PRIMITIVE_FIELDS_FAILURE';

export const MODEL_LIST_REQUEST = 'MODEL_LIST_REQUEST';
export const MODEL_LIST_SUCCESS = 'MODEL_LIST_SUCCESS';
export const MODEL_LIST_FAILURE = 'MODEL_LIST_FAILURE';

export const MODEL_LIST_COUNT_REQUEST = 'MODEL_LIST_COUNT_REQUEST';
export const MODEL_LIST_COUNT_SUCCESS = 'MODEL_LIST_COUNT_SUCCESS';
export const MODEL_LIST_COUNT_FAILURE = 'MODEL_LIST_COUNT_FAILURE';

export const AN_ENTITY_OF_MODEL_LIST_REQUEST =
  'AN_ENTITY_OF_MODEL_LIST_REQUEST';
export const AN_ENTITY_OF_MODEL_LIST_SUCCESS =
  'AN_ENTITY_OF_MODEL_LIST_SUCCESS';
export const AN_ENTITY_OF_MODEL_LIST_FAILURE =
  'AN_ENTITY_OF_MODEL_LIST_FAILURE';
