// account:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// participant

export const LIKE_WORKSHOP_REQUEST = 'LIKE_WORKSHOP_REQUEST';
export const LIKE_WORKSHOP_SUCCESS = 'LIKE_WORKSHOP_SUCCESS';
export const LIKE_WORKSHOP_FAILURE = 'LIKE_WORKSHOP_FAILURE';

export const LIKE_PRESENTATION_REQUEST = 'LIKE_PRESENTATION_REQUEST';
export const LIKE_PRESENTATION_SUCCESS = 'LIKE_PRESENTATION_SUCCESS';
export const LIKE_PRESENTATION_FAILURE = 'LIKE_PRESENTATION_FAILURE';

export const LIKED_WORKSHOPS_REQUEST = 'LIKED_WORKSHOPS_REQUEST';
export const LIKED_WORKSHOPS_SUCCESS = 'LIKED_WORKSHOPS_SUCCESS';
export const LIKED_WORKSHOPS_FAILURE = 'LIKED_WORKSHOPS_FAILURE';

export const LIKED_PRESENTATION_REQUEST = 'LIKED_PRESENTATION_REQUEST';
export const LIKED_PRESENTATION_SUCCESS = 'LIKED_PRESENTATION_SUCCESS';
export const LIKED_PRESENTATION_FAILURE = 'LIKED_PRESENTATION_FAILURE';

// WSS:

export const ALL_WORKSHOPS_REQUEST = 'ALL_WORKSHOPS_REQUEST';
export const ALL_WORKSHOPS_SUCCESS = 'ALL_WORKSHOPS_SUCCESS';
export const ALL_WORKSHOPS_FAILURE = 'ALL_WORKSHOPS_FAILURE';

export const ALL_PRESENTATIONS_REQUEST = 'ALL_PRESENTATIONS_REQUEST';
export const ALL_PRESENTATIONS_SUCCESS = 'ALL_PRESENTATIONS_SUCCESS';
export const ALL_PRESENTATIONS_FAILURE = 'ALL_PRESENTATIONS_FAILURE';

export const ALL_POSTERSESSIONS_REQUEST = 'ALL_POSTERSESSIONS_REQUEST';
export const ALL_POSTERSESSIONS_SUCCESS = 'ALL_POSTERSESSIONS_SUCCESS';
export const ALL_POSTERSESSIONS_FAILURE = 'ALL_POSTERSESSIONS_FAILURE';

export const ALL_SPONSORS_REQUEST = 'ALL_SPONSORS_REQUEST';
export const ALL_SPONSORS_SUCCESS = 'ALL_SPONSORS_SUCCESS';
export const ALL_SPONSORS_FAILURE = 'ALL_SPONSORS_FAILURE';

// snackbar

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';