// account:
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// participant

export const LIKE_WORKSHOP_REQUEST = 'LIKE_WORKSHOP_REQUEST';
export const LIKE_WORKSHOP_SUCCESS = 'LIKE_WORKSHOP_SUCCESS';
export const LIKE_WORKSHOP_FAILURE = 'LIKE_WORKSHOP_FAILURE';

export const LIKE_PRESENTATION_REQUEST = 'LIKE_PRESENTATION_REQUEST';
export const LIKE_PRESENTATION_SUCCESS = 'LIKE_PRESENTATION_SUCCESS';
export const LIKE_PRESENTATION_FAILURE = 'LIKE_PRESENTATION_FAILURE';

export const LIKED_WORKSHOPS_REQUEST = 'LIKED_WORKSHOPS_REQUEST';
export const LIKED_WORKSHOPS_SUCCESS = 'LIKED_WORKSHOPS_SUCCESS';
export const LIKED_WORKSHOPS_FAILURE = 'LIKED_WORKSHOPS_FAILURE';

export const LIKED_PRESENTATION_REQUEST = 'LIKED_PRESENTATION_REQUEST';
export const LIKED_PRESENTATION_SUCCESS = 'LIKED_PRESENTATION_SUCCESS';
export const LIKED_PRESENTATION_FAILURE = 'LIKED_PRESENTATION_FAILURE';

// WSS:

export const PRIMITIVE_FIELDS_REQUEST = 'PRIMITIVE_FIELDS_REQUEST';
export const PRIMITIVE_FIELDS_SUCCESS = 'PRIMITIVE_FIELDS_SUCCESS';
export const PRIMITIVE_FIELDS_FAILURE = 'PRIMITIVE_FIELDS_FAILURE';

export const MODEL_LIST_REQUEST = 'MODEL_LIST_REQUEST';
export const MODEL_LIST_SUCCESS = 'MODEL_LIST_SUCCESS';
export const MODEL_LIST_FAILURE = 'MODEL_LIST_FAILURE';

export const MODEL_LIST_COUNT_REQUEST = 'MODEL_LIST_COUNT_REQUEST';
export const MODEL_LIST_COUNT_SUCCESS = 'MODEL_LIST_COUNT_SUCCESS';
export const MODEL_LIST_COUNT_FAILURE = 'MODEL_LIST_COUNT_FAILURE';

// snackbar

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
