// account:
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// participant

export const LIKE_CARD_REQUEST = 'LIKE_CARD_REQUEST';
export const LIKE_CARD_SUCCESS = 'LIKE_CARD_SUCCESS';
export const LIKE_CARD_FAILURE = 'LIKE_CARD_FAILURE';

// WSS:

export const PRIMITIVE_FIELDS_REQUEST = 'PRIMITIVE_FIELDS_REQUEST';
export const PRIMITIVE_FIELDS_SUCCESS = 'PRIMITIVE_FIELDS_SUCCESS';
export const PRIMITIVE_FIELDS_FAILURE = 'PRIMITIVE_FIELDS_FAILURE';

export const MODEL_LIST_REQUEST = 'MODEL_LIST_REQUEST';
export const MODEL_LIST_SUCCESS = 'MODEL_LIST_SUCCESS';
export const MODEL_LIST_FAILURE = 'MODEL_LIST_FAILURE';

export const MODEL_LIST_COUNT_REQUEST = 'MODEL_LIST_COUNT_REQUEST';
export const MODEL_LIST_COUNT_SUCCESS = 'MODEL_LIST_COUNT_SUCCESS';
export const MODEL_LIST_COUNT_FAILURE = 'MODEL_LIST_COUNT_FAILURE';

// snackbar

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
