# Generated by Django 4.2.8 on 2024-01-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffteammember',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staffteammember',
            name='staff_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='staff.staffteam'),
        ),
    ]
