# Generated by Django 4.2.8 on 2024-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_alter_staff_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
