# Generated by Django 4.2.8 on 2025-03-18 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.UniqueUploadPath('staff')),
        ),
    ]
