# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet', models.FileField(upload_to='booklets/')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to='clips/')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('level', models.CharField(choices=[(None, 'Please Select'), ('msOrPhd', 'MS or PHD'), ('bsOrOther', 'BS or Other')], max_length=30, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='First Name (in Persian)')),
                ('family', models.CharField(max_length=250, verbose_name='Family Name (in Persian)')),
                ('name_english', models.CharField(max_length=250, verbose_name='First Name (in English)')),
                ('family_english', models.CharField(max_length=250, verbose_name='Family Name (in English)')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('age', models.PositiveSmallIntegerField()),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('introduction_method', models.CharField(choices=[(None, 'Please Select'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('poster', 'Poster'), ('friends', 'Friends'), ('other', 'Other')], default=None, max_length=250, verbose_name='How were you introduced to WSS?')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default=None, max_length=50)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('field_of_interest', models.CharField(blank=True, max_length=1500)),
                ('payment_status', models.CharField(choices=[('OK', 'پرداخت شده'), ('NO', 'پرداخت نشده')], default='NO', max_length=2)),
                ('grade', models.CharField(choices=[(None, 'Please Select'), ('msOrPhd', 'MS or PHD'), ('bsOrOther', 'BS or Other')], max_length=30)),
                ('is_student', models.BooleanField(default=False, verbose_name='I am a Student')),
                ('payment_id', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(blank=True, default=0)),
                ('participate_in_wss', models.BooleanField(default=True, help_text='Price: 135,000 Tomans for students, 150,000 Tomans for non-students', verbose_name='I want to participate in WSS Seminars')),
                ('question', models.CharField(choices=[(None, 'Please Select'), ('RPA', 'RPA'), ('Virtual Assistant', 'Virtual Assistant'), ('AR/VR/MR', 'AR/VR/MR'), ('Driverless Cars', 'Driverless Cars'), ('Recommendation Engines', 'Recommendation Engines'), ('Others', 'Others')], default=None, max_length=50, verbose_name="Which one of these Artificial Intelligence-related technologies do you think have the most impact on Iran's market?")),
                ('question_other', models.CharField(blank=True, max_length=500, verbose_name='Your answer')),
                ('sign_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=70)),
                ('student_number', models.CharField(blank=True, max_length=70)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(default=0, max_length=13, verbose_name='Phone Number')),
                ('major', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('short_link', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('number_of_clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='WSS.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='WSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('registration_open', models.BooleanField(default=False)),
                ('calendar_link', models.URLField(blank=True, null=True)),
                ('ical_link', models.URLField(blank=True, null=True)),
                ('proposal_link', models.URLField(blank=True, null=True)),
                ('participants_count_link', models.URLField(blank=True, null=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booklet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='WSS.Booklet')),
                ('main_clip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='WSS.Clip')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='WSS.Image')),
            ],
            options={
                'verbose_name': 'Winter Seminar Series',
                'verbose_name_plural': 'Winter Seminar Series',
                'ordering': ('-year',),
            },
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='wss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='WSS.WSS'),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_wss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='WSS.WSS', verbose_name='WSS'),
        ),
    ]
