# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('WSS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paid_workshops',
            field=models.ManyToManyField(blank=True, related_name='paid', to='events.Workshop'),
        ),
        migrations.AddField(
            model_name='participant',
            name='workshops',
            field=models.ManyToManyField(blank=True, to='events.Workshop'),
        ),
        migrations.AddField(
            model_name='image',
            name='wss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='WSS.WSS', verbose_name='WSS'),
        ),
        migrations.AddField(
            model_name='clip',
            name='wss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='WSS.WSS', verbose_name='WSS'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='wss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='WSS.WSS', verbose_name='WSS'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('email', 'payment_id')]),
        ),
    ]
