# Generated by Django 3.1.3 on 2020-11-16 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20201112_1807'),
        ('WSS', '0005_add_participant_user_and_wss_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='First Name (in Persian)')),
                ('family', models.CharField(max_length=250, verbose_name='Family Name (in Persian)')),
                ('name_english', models.CharField(max_length=250, verbose_name='First Name (in English)')),
                ('family_english', models.CharField(max_length=250, verbose_name='Family Name (in English)')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('age', models.PositiveSmallIntegerField()),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('introduction_method', models.CharField(choices=[(None, 'Please Select'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('poster', 'Poster'), ('friends', 'Friends'), ('other', 'Other')], default=None, max_length=250, verbose_name='How were you introduced to WSS?')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default=None, max_length=50)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('field_of_interest', models.CharField(blank=True, max_length=1500)),
                ('grade', models.CharField(choices=[(None, 'Please Select'), ('msOrPhd', 'MS or PHD'), ('bsOrOther', 'BS or Other')], max_length=30)),
                ('is_student', models.BooleanField(default=False, verbose_name='I am a Student')),
                ('payment_id', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(blank=True, default=0)),
                ('question', models.CharField(choices=[(None, 'Please Select'), ('RPA', 'RPA'), ('Virtual Assistant', 'Virtual Assistant'), ('AR/VR/MR', 'AR/VR/MR'), ('Driverless Cars', 'Driverless Cars'), ('Recommendation Engines', 'Recommendation Engines'), ('Others', 'Others')], default=None, max_length=50, verbose_name="Which one of these Artificial Intelligence-related technologies do you think have the most impact on Iran's market?")),
                ('question_other', models.CharField(blank=True, max_length=500, verbose_name='Your answer')),
                ('sign_timestamp', models.DateTimeField(auto_now=True)),
                ('paid_workshops', models.ManyToManyField(blank=True, related_name='paid', to='events.Workshop')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workshops', models.ManyToManyField(blank=True, to='events.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='WSS.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('current_wss', 'user_profile')},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='family',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='family_english',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='field_of_interest',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='introduction_method',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='job',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='paid_workshops',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='question',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='question_other',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='sign_timestamp',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='university',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='workshops',
        ),
    ]
