# Generated by Django 3.1.3 on 2020-11-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0007_convert_registration_fee_to_positive_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participate_in_wss',
        ),
    ]
