# Generated by Django 3.1.3 on 2020-11-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0008_remove_participant_participate_in_wss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_ref_id',
            field=models.CharField(default='NOT_PAYED', max_length=250),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
