# Generated by Django 3.1.3 on 2020-11-18 20:54

from django.db import migrations, models

def set_payment_data(apps, schema_editor):
    Participant = apps.get_model('WSS', 'Participant')
    for participant in Participant.objects.all():
        participant.payment_amount = participant.user_profile.paid_amount
        participant.payment_ref_id = participant.user_profile.payment_id
        participant.payment_timestamp = participant.user_profile.sign_timestamp
        participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0008_remove_participant_participate_in_wss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_ref_id',
            field=models.CharField(default='NOT_PAYED', max_length=250),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_payment_data)
    ]
