# Generated by Django 3.1.3 on 2020-12-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='wss',
            name='bsOrOther_participant_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='wss',
            name='msOrPhd_participant_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
