# Generated by Django 3.1.3 on 2020-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0009_remove_payment_status_add_payment_details_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[(None, 'Please Select'), ('msOrPhd', 'MS or PHD'), ('bsOrOther', 'BS or Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction_method',
            field=models.CharField(choices=[(None, 'Please Select'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('poster', 'Poster'), ('friends', 'Friends'), ('other', 'Other')], default=None, max_length=250, null=True, verbose_name='How were you introduced to WSS?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question',
            field=models.CharField(choices=[(None, 'Please Select'), ('RPA', 'RPA'), ('Virtual Assistant', 'Virtual Assistant'), ('AR/VR/MR', 'AR/VR/MR'), ('Driverless Cars', 'Driverless Cars'), ('Recommendation Engines', 'Recommendation Engines'), ('Others', 'Others')], default=None, max_length=50, null=True, verbose_name="Which one of these Artificial Intelligence-related technologies do you think have the most impact on Iran's market?"),
        ),
    ]
