# Generated by Django 3.1.3 on 2020-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0014_userprofile_favorite_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
