# Generated by Django 3.1.3 on 2020-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0010_remove_email_from_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family_english',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name_english',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_workshops',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question_other',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workshops',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family',
            field=models.CharField(max_length=250, verbose_name='Family Name (in English)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=250, verbose_name='First Name (in English)'),
        ),
    ]
