# Generated by Django 3.1.3 on 2020-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0010_add_participant_limits_to_wss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wss',
            old_name='bsOrOther_participant_limit',
            new_name='bs_participant_limit',
        ),
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.CharField(choices=[(None, 'Please Select'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD or Higher', 'PhD or Higher')], max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[(None, 'Please Select'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD or Higher', 'PhD or Higher')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction_method',
            field=models.CharField(choices=[(None, 'Please Select'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Poster', 'Poster'), ('Friends', 'Friends'), ('Other', 'Other')], default=None, max_length=250, null=True, verbose_name='How were you introduced to WSS?'),
        ),
    ]
