# Generated by Django 3.1.3 on 2020-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0011_change_choices_in_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction_method',
            field=models.CharField(choices=[(None, 'Please Select'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Poster', 'Poster'), ('Linkedin', 'Linkedin'), ('YouTube', 'YouTube'), ('Friends', 'Friends'), ('Other', 'Other')], default=None, max_length=250, null=True, verbose_name='How were you introduced to WSS?'),
        ),
    ]
