# Generated by Django 3.1.3 on 2020-11-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0011_remove_excesive_fields_from_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='family',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
