# Generated by Django 3.1.3 on 2020-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0012_change_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wss',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
