# Generated by Django 3.1.3 on 2020-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_baseevent__url_allow_blank'),
        ('WSS', '0013_wss__description_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered_workshops',
            field=models.ManyToManyField(blank=True, related_name='participants', to='events.Workshop'),
        ),
    ]
