# Generated by Django 3.1.3 on 2020-11-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_tag'),
        ('WSS', '0013_making_userprofile_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_tags',
            field=models.ManyToManyField(blank=True, null=True, to='events.WssTag', verbose_name='Favorite tags'),
        ),
    ]
