# Generated by Django 3.1.3 on 2020-12-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0014_participant_registered_workshops'),
    ]

    operations = [
        migrations.AddField(
            model_name='wss',
            name='participant_workshop_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
