# Generated by Django 3.1.3 on 2020-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0015_wss_participant_workshop_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wss',
            name='workshop_registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
