# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from datetime import date
from django.db import migrations


def add_WSS_2019_instance(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    WSS.objects.create(
        year=2019,
        start_date=date(2020, 1, 2),
        end_date=date(2020, 1, 3)
    )


def rollback(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    WSS.objects.get(year=2019).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('WSS', '0016_wss_workshop_registration_open'),
    ]

    operations = [
        migrations.RunPython(add_WSS_2019_instance, rollback)
    ]
