# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from datetime import date
from django.db import migrations


def forward(apps, schema_editor):
    Sponsor = apps.get_model('WSS', 'Sponsor')
    Sponsorship = apps.get_model('WSS', 'Sponsorship')
    WSS = apps.get_model('WSS', 'WSS')

    wss = WSS.objects.get(year=2019)

    sponsor = Sponsor.objects.create(
        name='Fanap',
        logo='logos/Fanap_Logo_min.png',
        url='https://fanap.ir/'
    )
    Sponsorship.objects.create(
        wss=wss,
        sponsor=sponsor,
        is_main=True
    )


def rollback(apps, schema_editor):
    Sponsor = apps.get_model('WSS', 'Sponsor')
    Sponsorship = apps.get_model('WSS', 'Sponsorship')
    WSS = apps.get_model('WSS', 'WSS')

    wss = WSS.objects.get(year=2019)
    sponsorship = Sponsorship.objects.get(wss=wss)
    sponsor_id = sponsorship.sponsor.id
    sponsorship.delete()
    Sponsor.objects.get(id=sponsor_id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('WSS', '0017_add_WSS_2019'),
    ]

    operations = [
        migrations.RunPython(forward, rollback)
    ]
