# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from datetime import date
from django.db import migrations

def add_7th_WSS_instance(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    WSS.objects.create(
        year=2021,
        start_date=date(2022,2,24),
        end_date=date(2022,2,27)
    )

def rollback(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    WSS.objects.get(year=2021).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0018_add_WSS_2019_sponsor'),
    ]

    operations = [
        migrations.RunPython(add_7th_WSS_instance, rollback)
    ]
