# Generated by Django 3.1.3 on 2022-02-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0020_auto_20220210_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='persian_first_name',
            field=models.CharField(
                max_length=100, null=True, blank=True, default=None, verbose_name="Persian first name"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persian_last_name',
            field=models.CharField(
                max_length=100, null=True, blank=True, default=None, verbose_name="Persian last name"),
        ),
    ]
