# Generated by Django 3.1.3 on 2023-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0021_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='off_percentage',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online_attendant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wss',
            name='in_person_fee_bias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
