# Generated by Django 3.1.3 on 2023-03-11 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WSS', '0022_auto_20230224_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=36, unique=True, verbose_name='authority')),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('wss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WSS.wss', verbose_name='winter seminar series')),
            ],
        ),
    ]
