# Generated by Django 1.11.26 on 2020-10-22 19:47
from __future__ import unicode_literals
from django.db import migrations, models


def add_title_to_WSS_model(apps, schema_editor):
    year_to_title = {
        2015: "1st",
        2016: "2nd",
        2017: "3rd",
        2018: "4th",
        2019: "5th",
        2020: "6th",
        2021: "7th",
        2022: "8th",
    }
    WSS = apps.get_model('WSS', 'WSS')
    for w in WSS.objects.all():
        title = year_to_title[w.year]
        w.title = title
        w.save()


def rollback(apps, schema_editor):
    WSS = apps.get_model('WSS', 'WSS')
    for w in WSS.objects.all():
        w.title = ""
        w.save()


class Migration(migrations.Migration):
    dependencies = [
        ('WSS', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wss',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_title_to_WSS_model, rollback),
    ]
