# Generated by Django 3.1.3 on 2023-03-29 12:51

from django.db import migrations, models


def update_is_online_attendants(apps, _):
    Participant = apps.get_model("WSS", "Participant")
    Participant.objects.filter(user_profile__is_online_attendant=True).update(is_online_attendant=True)


class Migration(migrations.Migration):
    dependencies = [
        ('WSS', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_online_attendant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=update_is_online_attendants,
            reverse_code=lambda *args, **kwargs: None,
        )
    ]
