# Generated by Django 3.1.3 on 2023-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0024_auto_20230329_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction_method',
            field=models.CharField(choices=[(None, 'Please Select'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('SMS', 'SMS'), ('Email', 'Email'), ('Twitter', 'Twitter'), ('Poster', 'Poster'), ('Linkedin', 'Linkedin'), ('Quera', 'Quera'), ('YouTube', 'YouTube'), ('Friends', 'Friends'), ('Other', 'Other')], default=None, max_length=250, null=True, verbose_name='How were you introduced to WSS?'),
        ),
    ]
