# Generated by Django 4.2.8 on 2025-03-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0004_alter_participationattachment_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participation')),
            ],
        ),
    ]
