# Generated by Django 4.2.8 on 2023-12-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('count', models.IntegerField(default=-1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participationtype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentdiscount')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participationtype')),
            ],
        ),
    ]
