# Generated by Django 5.1.4 on 2025-03-20 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_participationattachment_attachment'),
        ('payment', '0003_alter_paymentdiscount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_numbers', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('group_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('participant_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentdiscount')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participationplan')),
            ],
        ),
    ]
