# Generated by Django 4.2.8 on 2024-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AddField(
            model_name="workshop",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
