# Generated by Django 4.2.8 on 2024-02-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workshop_poster_workshop_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
