# Generated by Django 4.2.8 on 2024-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopsession',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
