# Generated by Django 4.2.8 on 2024-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_workshopsession_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="designation",
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
