# Generated by Django 4.2.8 on 2024-02-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_event_description_alter_speaker_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labtalk",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.speaker"
            ),
        ),
        migrations.AlterField(
            model_name="postersession",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.speaker"
            ),
        ),
        migrations.AlterField(
            model_name="seminar",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.speaker"
            ),
        ),
        migrations.AlterField(
            model_name="workshopsession",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.speaker"
            ),
        ),
    ]
