# Generated by Django 4.2.8 on 2025-01-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_labtalk_speaker_alter_postersession_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
