# Generated by Django 4.2.8 on 2025-01-04 16:51

from django.db import migrations


def set_default_event_for_workshops(apps, schema_editor):
    Workshop = apps.get_model('core', 'Workshop')
    Event = apps.get_model('core', 'Event')
    
    # Get the default event. You can choose the first one or use another criterion.
    default_event = Event.objects.get(id=1)  # Replace with your default event if needed.
    
    if default_event:
        # Update past workshops that do not have an associated event
        workshops_without_event = Workshop.objects.filter(event__isnull=True)
        workshops_without_event.update(event=default_event)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workshop_event'),
    ]

    operations = [
        migrations.RunPython(set_default_event_for_workshops),
    ]
