# Generated by Django 4.2.8 on 2025-01-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_previous_workshop_foreignkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
