# Generated by Django 4.2.8 on 2025-01-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workshop_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='event',
        ),
    ]
