# Generated by Django 4.2.8 on 2025-03-18 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_poster_session_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postersessionimage',
            name='image',
            field=models.FileField(upload_to=core.models.UniqueUploadPath('poster-images')),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UniqueUploadPath('speakers')),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UniqueUploadPath('posters')),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UniqueUploadPath('thumbnails')),
        ),
    ]
