# Generated by Django 4.2.8 on 2023-12-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_persian', models.CharField(blank=True, max_length=50)),
                ('last_name_persian', models.CharField(blank=True, max_length=50)),
                ('national_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='participant/')),
                ('bio', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participantinfo')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='participation/')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participation')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='participation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participationtype'),
        ),
        migrations.AddField(
            model_name='participant',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participant.participantinfo'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
