# Generated by Django 4.2.8 on 2024-02-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spotplayer", "0001_initial"),
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="spotplayer_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spotplayer.spotplayerlicense",
            ),
        ),
        migrations.AddField(
            model_name="participationplan",
            name="spotplayer_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spotplayer.spotplayercourse",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="participant.participantinfo",
            ),
        ),
    ]
