# Generated by Django 4.2.8 on 2024-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
