# Generated by Django 4.2.8 on 2024-01-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_password_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantinfo',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='participantinfo',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='participantinfo',
            name='first_name_persian',
        ),
        migrations.RemoveField(
            model_name='participantinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='participantinfo',
            name='last_name_persian',
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='fields_of_interest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='grade',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('P', 'PhD')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='introduction_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='is_open_to_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
