# Generated by Django 4.2.8 on 2024-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participant", "0003_remove_participantinfo_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantinfo",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
