# Generated by Django 4.2.8 on 2025-03-18 20:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_participant_password_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.UniqueUploadPath('participation')),
        ),
    ]
